import re
import html
import streamlit as st

# =============================================================================
# PAGE CONFIGURATION
# =============================================================================
st.set_page_config(
    page_title="Global CETP Inhibitors Market Preview | Menarini",
    page_icon="🩺",
    layout="wide",
    initial_sidebar_state="expanded",
)

# =============================================================================
# THEME COLORS
# =============================================================================
BURGUNDY = "#5B0E2D"
BURGUNDY_DARK = "#3A071C"
MID_BURGUNDY = "#8D1645"
SOFT_ROSE = "#D8A7B1"
GOLD = "#C9A227"
LIGHT_GREY = "#F4F5F7"
WHITE = "#FFFFFF"
DARK_TEXT = "#2B2B2B"
MUTED_TEXT = "#666666"
BORDER_GREY = "#E1E4E8"

# =============================================================================
# LOGIN CREDENTIALS
# =============================================================================
USERNAME = "SMR"
PASSWORD = "SMR@2026"

# =============================================================================
# REPORT TEXT
# =============================================================================
REPORT_TEXT = r"""
Global CETP Inhibitors Market, 2025–2035: Obicetrapib-Led Lipid-Lowering Opportunity, TAM/SAM/SOM Buildout & Strategic Positioning for Menarini
## 1. Executive Overview & Strategic Snapshot ($Mn, %, 2025–2035)
1.1. Strategic Market Thesis
The global landscape for lipid-lowering therapies (LLT) is currently undergoing a structural transformation, characterized by the emergence of high-efficacy oral alternatives to established injectable biologics. The cholesteryl ester transfer protein (CETP) inhibitor class, once sidelined due to the historical clinical failures of earlier-generation assets, is being revived through the development of obicetrapib.1 Analysis indicates that the current market represents a unique category-creation opportunity rather than a mature, multi-product space. As of 2025, the strict CETP inhibitor market generates zero commercial revenue, reflecting its pre-approval status.1 However, the commercial potential is anchored in a massive, established lipid-lowering treatment landscape where a significant proportion of high-risk patients fail to achieve low-density lipoprotein cholesterol (LDL-C) goals.1
Obicetrapib is positioned as the first next-generation CETP inhibitor to successfully decouple potent LDL-C lowering from the off-target safety issues and efficacy neutralities that plagued predecessors such as torcetrapib and evacetrapib.1 This asset serves as the primary vehicle for class revival, targeting the LDL-C gap in patients who remain uncontrolled despite maximally tolerated statin therapy.1 The strategic thesis for Menarini focuses on the commercialization of obicetrapib monotherapy and its fixed-dose combination (FDC) with ezetimibe across Europe, the UK, and Switzerland.1 Success is predicated on overcoming historical class skepticism through a robust evidence base, including the pivotal Phase 3 BROADWAY, BROOKLYN, and TANDEM trials, alongside the ongoing PREVAIL cardiovascular outcomes trial (CVOT).1
1.2. Market Size Snapshot
The market sizing architecture differentiates between the currently monetized lipid-lowering landscape, defined as the Practical Total Addressable Market (TAM), and the specific opportunity for CETP inhibitors post-approval, defined as the Serviceable Addressable Market (SAM) and Menarini’s Serviceable Obtainable Market (SOM). The global practical TAM is reset to US$31.8 billion in 2025, reflecting the total revenue generated by existing therapies including statins, ezetimibe, bempedoic acid, PCSK9 monoclonal antibodies, and inclisiran.1
TABLE 1: Executive Market Sizing Summary ($Mn, 2025–2035)
Market Layer  2025 Value  2030 Value  2035 Value  2025–35 CAGR
Global Practical TAM  31,800.0  38,319.0  46,174.3  3.8%
Menarini Territory TAM  9,015.0  10,643.6  12,568.4  3.4%
CETP-Addressable SAM (Revenue Potential)  0.0  6,688.9  6,709.2  Activated 2027
Menarini-Capturable SOM (Revenue)  0.0  181.7  468.1  Launch-driven
Strict CETP Inhibitor Revenue  0.0  181.7  468.1  Launch-driven

Analysis indicates that while the global TAM grows at a steady 3.8%, the Menarini-specific opportunity (SOM) experiences a rapid ramp-up following expected 2027 reimbursement activation, reaching US$468.1 million by 2035.1 The practical TAM reflects the existing "budget pool" for lipid management, while the SAM narrows this to the specific uncontrolled and high-risk patients that obicetrapib will target.1
1.3. Executive Growth Indicators
The trajectory of the CETP inhibitor market is defined by a strategic shift from monotherapy volume to high-value combination treatment. The forecast indicates that while obicetrapib monotherapy will drive early volume in the 2027–2029 period, the obicetrapib/ezetimibe FDC will become the primary revenue driver by the mid-2030s.1
Product Split Evolution: By 2035, the FDC is expected to account for 61.9% of total Menarini SOM revenue, reflecting the clinical trend toward earlier intensification and the convenience of single-pill combinations.1
Geographic Concentration: Menarini’s opportunity is concentrated in Germany, which represents the highest priority market contributing US$76.4 million and the UK at US$72.2 million.1
Launch Velocity and Ramp: Revenue generation is strictly launch-flagged, with no commercial revenue projected before 2027. The first full five years of launch (2027–2032) are critical for establishing specialist trust and securing inclusion in clinical guidelines.1
Sensitivity to Outcomes Data: Analysis indicates that positive results from the PREVAIL CVOT trial serve as a major upside lever, potentially increasing adoption multipliers by 15% to 35% above base-case projections in the post-2030 window.1
1.4. Strategic Implications for Menarini
Menarini’s role in this category-creation effort is focused on the successful navigation of European Health Technology Assessment (HTA) and payer landscapes. The opportunity is concentrated in high-risk patient groups, specifically those with Heterozygous Familial Hypercholesterolemia (HeFH) and established Atherosclerotic Cardiovascular Disease (ASCVD) who fail to reach LDL-C targets on standard oral therapies.1
Commercial adoption is expected to depend on the ability to position obicetrapib as a "biologic-like" oral alternative. Menarini must win in the uncontrolled high-risk pool, which represents the primary demand engine for early adoption.3 Priority markets include Germany, the UK, and France, where infrastructure for lipid management is most advanced and the addressable patient pool is largest.1 Strategic efforts must be directed toward medical education that addresses the historical CETP failures by emphasizing obicetrapib’s high selectivity and lack of blood pressure side effects.1 Furthermore, positioning the FDC as a superior oral alternative to bempedoic acid/ezetimibe combinations—leveraging the superior 48.6% LS mean LDL-C reduction observed in the TANDEM trial—will be essential for maximizing blended net price per patient.1
## 2. Market Definition, Scope & TAM/SAM/SOM Architecture
2.1. CETP Inhibitor Market Definition
The CETP inhibitor market is defined as the commercial revenue generated specifically by pharmacological agents designed to inhibit the cholesteryl ester transfer protein to lower LDL-C and reduce major adverse cardiovascular events (MACE). In the 2025–2035 horizon, this is a "near-launch" category represented by obicetrapib.1 The market is distinct from the broader cardiovascular drug market, which includes hypertension and antithrombotic therapies, and is focused exclusively on lipid modification.1
The product scope for this analysis is limited to:
Obicetrapib 10mg Monotherapy: An oral, selective small molecule.2
Obicetrapib 10mg / Ezetimibe 10mg FDC: A fixed-dose combination designed for enhanced LDL-C lowering.7
2.2. Disease Scope and Indications
The addressable population is segmented by clinical risk and the regulatory label expectations set during the EMA and UK submissions. The core indications submitted include the treatment of adults with primary hypercholesterolemia (both HeFH and non-familial) and mixed dyslipidemia.2 Within these groups, the analysis prioritizes:
Secondary Prevention (ASCVD): Patients with established cardiovascular disease requiring aggressive LDL-C targets of <55 mg/dL per 2025 ESC/EAS updates.1
HeFH Patients: A high-risk genetic subgroup where prevalence is approximately 1 in 250 individuals, characterized by significant goal non-attainment.1
Statin-Intolerant Populations: Patients unable to use maximally tolerated statins, representing a key oral non-statin candidate pool.1
2.3. Sizing architecture and Logic
The report employs a strict revenue recognition logic where the category size is $0 until the point of regulatory approval and subsequent reimbursement. This architecture prevents the overlap of CETP revenue with current therapy pools, which are treated as the "Budget TAM."
TABLE 2: Market Layer Architecture & Definitions
Market Layer  Definition  Starts From  Use in Forecast  Relevance to Menarini
Strict CETP Market  Revenue from approved CETP inhibitors only  2027 (Launch)  Core growth metric  Represents client product sales
Practical TAM  Current revenue of all relevant lipid-lowering therapies  2025  Ceiling context  Competitive revenue pool
SAM  CETP-addressable subset post-label and access filters  2027  Eligible pool  Territory volume potential
SOM  Obicetrapib revenue in Menarini territory  2027  Financial forecast  Direct client revenue and profit

Analysis indicates that the full cardiovascular drug market is excluded because it contains high-volume, unrelated classes such as beta-blockers and anti-hypertensives. Furthermore, the full dyslipidemia population is not counted as SAM; the filter only includes patients who are diagnosed, treated, and remain above LDL-C targets, as these represent the clinically eligible pool for a premium branded add-on therapy.1
## 3. CETP Mechanism, Class History & Repositioning Logic
3.1. CETP Biology and Mechanism of Action
CETP is a plasma protein that facilitates the exchange of cholesteryl esters from HDL to apoB-containing lipoproteins (VLDL and LDL) in exchange for triglycerides.1 Historically, the industry focused on CETP inhibition as a mechanism to raise HDL-C, the "good cholesterol." However, contemporary clinical logic has shifted toward reducing the atherogenic burden of LDL-C and apoB particles.3 Obicetrapib is a highly selective and potent inhibitor that achieves robust LDL-C reduction at a low 10mg dose, differentiating its pharmacological profile from earlier, less selective molecules.6
3.2. Historical Class Failures and Commercial Lessons
The CETP class has a volatile clinical history that necessitates a strategic rebuilding of physician and payer trust. Analysis of historical assets reveals that failures were largely due to off-target effects or lack of clinical event reduction rather than a failure of the mechanism itself.1
TABLE 3: Historical CETP Asset Comparison & Lessons
Asset  Company  Status  Key Issue / Outcome  Commercial Lesson
Torcetrapib  Pfizer  Discontinued  Off-target toxicity / mortality  Safety is paramount; avoid BP elevation
Dalcetrapib  Roche / DalCor  Limited  Efficacy neutrality in broad pool  Potency in LDL-C reduction is required
Evacetrapib  Eli Lilly  Discontinued  Failed to show outcomes benefit  Lipid changes must translate to MACE
Anacetrapib  Merck  Discontinued  Long half-life / Commercial stop  Launch timing and differentiation matter

The clinical trajectory demonstrates that obicetrapib avoids these historical pitfalls by maintaining a neutral blood pressure profile and achieving substantially higher LDL-C reduction (up to ~50% in combination) than predecessors.7
3.3. Category Repositioning Logic
Obicetrapib changes the class narrative by positioning itself as a highly selective oral alternative that bridges the efficacy gap between statins/ezetimibe and injectable biologics.3 To rebuild confidence, the commercial strategy must lead with the "Next-Generation" label, supported by the clean safety profile seen in Phase 3 trials.4 Payer and physician acceptance will depend on the dissemination of the BROADWAY and BROOKLYN data, which show consistent results across diverse populations.1 Outcomes data from the ongoing PREVAIL trial remains strategically vital, as proved cardiovascular benefit is the threshold for broad guideline inclusion and premium reimbursement in the post-statin landscape.1
## 4. Disease Burden & Addressable Patient Pool
4.1. Hypercholesterolemia Prevalence and High-Risk Segments
Cardiovascular disease remains the leading cause of death in the WHO European region, causing over 10,000 deaths per day.14 Circulatory diseases specifically cause 32% of all deaths in the EU.15 Adult populations in core Menarini territories exhibit hypercholesterolemia prevalence rates between 40% and 49%.1 The primary commercial challenge is the "funneling" of this broad population into a reachable, high-risk, uncontrolled patient base.
TABLE 4: Menarini Territory Patient Funnel Analysis (Mn Patients)
Funnel Stage  2025  2030  2035  Interpretation
Adult Population  507.4  508.5  509.7  Total population base
Diagnosed Patients  161.1  161.8  162.6  Diagnosis rates average 60%–65%
Treated Patients  102.3  103.1  103.9  ~63% of diagnosed receive treatment
Uncontrolled LDL-C  42.1  42.4  42.8  ~41% of treated patients fail to hit goals
CETP-Relevant Pool  17.5  17.6  17.8  Filtered for high-risk and ASCVD
Commercially Reachable  4.4  4.4  4.5  Specialist reach and access narrowed pool

Analysis indicates that the "uncontrolled high-risk" pool is the critical demand engine. While the total hypercholesterolemic population is large, the commercially addressable market is narrowed by the requirement for specialist referral and the anticipated HTA restrictions that favor established generic therapies for low-risk patients.1
4.2. Country-Level Demand and Distribution
Demand is highly concentrated in Germany, which maintains the largest uncontrolled LDL-C pool in the territory. Italy and France follow, though their reachable pools are filtered more aggressively by specialist infrastructure and access predictability scores.1
TABLE 5: 2025 Country-Level Demand Engine Summary (Mn Patients)
Country  Diagnosed  Treated  Uncontrolled  CETP-Relevant  Reachable Pool
Germany  24.84  16.89  7.09  3.40  1.02
France  18.98  12.53  5.39  2.53  0.68
United Kingdom  18.29  12.07  5.19  2.39  0.67
Italy  16.14  10.49  4.62  2.12  0.53
Spain  12.03  7.58  3.41  1.53  0.35
Switzerland  2.51  1.75  0.70  0.32  0.10

Analysis demonstrates that Germany’s high treatment rate (68%) and physician infrastructure lead to a reachable pool of over 1 million patients, making it the anchor for the European launch.1 Conversely, while Italy has a large diagnosed population, the specialist reach factor (0.25) significantly reduces the early reachable pool, suggesting a more selective commercial ramp.1
## 5. Current Treatment Landscape & Revenue Pool Benchmark ($Mn)
5.1. The Lipid-Lowering Treatment Pathway
The current lipid-lowering environment is a mature, volume-driven landscape where statins serve as the entrenched first-line therapy. The emergence of non-statin oral add-ons and high-efficacy injectables has created a tiered escalation pathway.
TABLE 6: Current Therapy Class Landscape & Pathway Role
Therapy Class  Route  Role in Pathway  Pricing Tier  Relevance to CETP Entry
Generic Statins  Oral  1st-line standard  Low  Entrenched volume backbone
Ezetimibe  Oral  1st-line add-on  Low  Sequencing benchmark
Bempedoic Acid  Oral  Oral non-statin  Branded  Closest branded oral comparator
PCSK9 mAbs  Injectable  High-risk escalation  High  High-efficacy benchmark
Inclisiran  Injectable  Long-acting specialist  High  Competitor for similar high-risk patients

5.2. Practical TAM by Therapy Class ($Mn)
The practical TAM represents the total monetized opportunity within which CETP inhibitors will compete for value share. This US$9 billion territory pool (2025) is dominated by premium injectables, which represent over half of total revenue despite serving a minority of patients.1
TABLE 7: Relevant Treatment TAM by Therapy Class ($Mn)
Therapy Class  2025 Revenue  2030 Revenue  2035 Revenue  CAGR
PCSK9 mAbs  3,065.1  3,618.8  4,273.2  3.4%
Inclisiran  1,442.4  1,702.9  2,010.9  3.4%
Generic Statins  1,622.7  1,915.9  2,262.3  3.4%
Ezetimibe (Add-on)  1,081.8  1,277.2  1,508.2  3.4%
Bempedoic Acid  721.2  851.5  1,005.5  3.4%
Other / Specialty  1,081.8  1,277.2  1,508.2  3.4%
Territory Total  9,015.0  10,643.6  12,568.4  3.4%

Insight: The dominance of the injectable biologics segment (PCSK9/Inclisiran) sets a high-efficacy ceiling for the market. If obicetrapib can demonstrate similar MACE reduction with oral convenience, it can potentially substitute value from this ~$6.3 billion pool by 2035.4 The growth of bempedoic acid (10.5% CAGR in secondary research estimates) further validates the market’s willingness to pay for branded oral non-statins.1
5.3. Practical TAM by Geography and Segment
Germany represents the largest geographic revenue pool, accounting for US$1.65 billion in 2025 practical TAM.1 From a patient segment perspective, the ASCVD uncontrolled pool is the highest-value segment, representing 46% of the territory's treatment revenue.1
TABLE 8: Menarini Territory Practical TAM by Patient Segment ($Mn)
Patient Segment  2025  2030  2035  Interpretation
ASCVD / High-Risk  4,146.9  4,896.1  5,781.4  Priority intensification segment
Hypercholesterolemia  2,524.2  2,980.2  3,519.1  Main label-relevant pool
HeFH  1,262.1  1,490.1  1,759.6  High-unmet need specialty group
Mixed Dyslipidemia  811.4  957.9  1,131.2  Adjacent label-expansion pool
Statin Intolerant  270.5  319.3  377.1  Critical oral non-statin niche

Demand is driven by the tightening of ESC/EAS guidelines, which favor earlier combination therapy to reach target LDL-C levels below 1.8 mmol/L and 1.4 mmol/L.8 This clinical trend supports the positioning of the obicetrapib/ezetimibe FDC as an early escalation option.16
## 6. Unmet Need, LDL-C Control Gap & SAM Conversion
6.1. The LDL-C Control Gap in Europe
Despite the availability of generic and branded therapies, LDL-C goal attainment remains suboptimal across Europe. Data from the DA VINCI study indicate that only 31.1% of high and very-high risk patients achieve risk-based targets.4 This non-attainment is driven by:
Statin Resistance and Intolerance: Approximately 10% of high-risk patients are statin-intolerant or require non-statin add-ons to reach goal.1
Injection Burden: A significant portion of the patient and prescriber base is resistant to self-injection or the cold-chain logistics required for PCSK9 monoclonal antibodies.3
Treatment Intensification Gaps: Clinical inertia often prevents the escalation to high-efficacy therapies, creating a pool of "undertreated" high-risk individuals.7
6.2. SAM Conversion Logic
The SAM represents the addressable "commercial ceiling" after filtering the theoretical patient pool by expected labeling and payer access hurdles. The model converts the uncontrolled LDL-C pool into SAM based on a base eligibility factor (0.82) and a reachability factor (1.0) in the base case.1
TABLE 9: TAM-to-SAM Revenue Potential Bridge ($Mn, 2035)
Step  Pool / Revenue  Conversion  Output  Rationale
Practical TAM  12,568.4  N/A  12,568.4  Total territory relevant pool
Uncontrolled Filter  12,568.4  42.1%  5,291.3  Targets only those failing goals
Label / Access  5,291.3  82.0%  4,338.9  Filtered for label and HTA
SAM Potential  6,709.2  Formula  6,709.2  Calculated pre-adoption ceiling

Analysis indicates that the SAM Potential is not the actual revenue, but the pre-adoption revenue ceiling. Revenue only begins to flow once country launch flags are activated, ensuring consistency with the model’s "zero revenue pre-approval" rule.1
## 7. Obicetrapib Clinical Evidence & Pipeline Positioning
7.1. Obicetrapib Asset Profile
Obicetrapib is a next-generation CETP inhibitor developed to overcome the potency and safety limitations of earlier class assets. Clinical evidence from Phase 2 and 3 programs demonstrates that obicetrapib, both as monotherapy and in combination with ezetimibe, achieves biologic-like LDL-C reduction through an oral mechanism.4
TABLE 10: Obicetrapib Pivotal Trial Evidence Summary
Trial  Phase  Population  Result  Commercial Implication
BROADWAY  Phase 3  ASCVD / HeFH  ~35% LDL reduction  Supports base lipid label
BROOKLYN  Phase 3  HeFH  36.3% reduction  Specialist segment validator
TANDEM  Phase 3  High-risk/ASCVD  48.6% reduction  Driver for FDC positioning
ROSE2  Phase 2  LLT-treated  59% reduction  Benchmarks vs biologics
PREVAIL  Phase 3  ASCVD  Ongoing  Long-term adoption accelerator

7.2. Safety and Differentiation
Historical CETP class concerns focused on off-target hypertensive effects (torcetrapib) and lack of potency in broad populations (dalcetrapib).1 Analysis indicates that obicetrapib maintains a safety profile comparable to placebo, with no observed impact on blood pressure.4 This differentiation is critical for securing clinical confidence. Furthermore, obicetrapib’s high selectivity for CETP over other lipid-transfer proteins reduces the risk of non-specific lipid changes.3
7.3. Pipeline and Expansion Potential
The RUBENS program, initiated in December 2025, evaluates obicetrapib in type 2 diabetes and metabolic syndrome, populations that require aggressive lipid lowering but often face barriers to intensification.5 Success in RUBENS could expand the SAM in the post-2030 period. Additionally, exploratory analyses from the BROADWAY trial indicate a potential link between CETP inhibition and neurodegeneration biomarkers (p-tau217), presenting a long-term "narrative optionality" in Alzheimer’s disease that is not currently included in the core lipid market sizing.1
## 8. Regulatory Pathway, Label Scenarios & Launch Timing
8.1. Regulatory Submission and Status
In August 2025, the EMA validated the Marketing Authorisation Applications (MAAs) for both obicetrapib monotherapy and the obicetrapib/ezetimibe FDC.2 Parallel submissions were accepted by the MHRA (UK) and Swissmedic.5 Approval decisions are anticipated in the second half of 2026, positioning 2027 as the first full commercial revenue year.5
8.2. Country Launch Waves and Activation
Launch activation is staggered across the Menarini territory based on country-specific reimbursement pathways and HTA evidence requirements.
TABLE 11: Menarini Territory Launch Sequencing & Access Logic
Country  Reimbursement  Launch Wave  Access Pathway Logic  Access Risk
Germany  2027  Wave 1  AMNOG early reimbursed launch  Moderate
United Kingdom  2027  Wave 1  NICE cost-effectiveness hurdle  High
France  2028  Wave 2  HAS/CEPS price-volume control  Moderate
Switzerland  2028  Wave 2  Premium market specialty access  Low
Italy  2028  Wave 2  Regional implementation variation  High
Spain  2028  Wave 2  Budget pressure/regional delays  High

The model assumes that revenue starts strictly from the reimbursement year. Germany and the UK are prioritized due to their established infrastructure for specialist-led early access. WAVE 2 countries follow once national pricing negotiations are finalized.1
## 9. Pricing, Reimbursement & Monetization Architecture ($/Patient/Year)
9.1. Pricing Methodology for Pre-Approval Asset
Obicetrapib is priced as a premium branded oral therapy. Analysis indicates that the pricing strategy must navigate the space between low-cost generic ezetimibe and high-cost injectable biologics. The "mid-branded" pricing tier is anchored to bempedoic acid (Nustendi/Nilemdo), which serves as the closest oral benchmark.1
TABLE 12: Country Net Pricing and Gross-to-Net (GTN) Assumptions
Country  Mono Net Price  FDC Net Price  GTN Factor  Pricing Rationale
Germany  1,050  1,312.5  0.72  AMNOG mid-branded benchmark
Switzerland  1,200  1,500.0  0.75  Premium market capability
France  900  1,125.0  0.68  HAS/CEPS mid-tier proxy
United Kingdom  875  1,093.8  0.70  NICE cost-effectiveness floor
Italy  850  1,062.5  0.66  Regional implementation pressure
Spain  800  1,000.0  0.65  Budget-conscious benchmark

9.2. Monetization Formula and Revenue Per Patient
The monetization model accounts for annual price erosion to avoid unrealistic long-term revenue projections. Erosion factors range from 1.2% in core markets to 1.8% in the "Rest of Europe," reflecting standard HTA price reviews and generic entry in adjacent lipid classes.1
9.3. HTA Evidence and Payer Requirements
Payer access will depend on the demonstration of incremental benefit over generic ezetimibe and branded bempedoic acid. NICE (UK) and HAS (France) are expected to scrutinize the TANDEM trial data, which achieved a 48.6% LDL-C reduction—significantly higher than the ~18% reduction typically associated with bempedoic acid.12 Proactive health-economic modeling is required to position the FDC as a "pre-injectable" step that avoids the higher budgetary burden of PCSK9/inclisiran therapies.1
## 10. Market Size & Forecast, 2025–2035 ($Mn, Patients, %)
10.2. Market Layer Forecast ($Mn)
The market demonstrates a rapid category-creation ramp following the 2027 launch wave. While the underlying lipid TAM remains stable, the CETP category builds from zero to a significant specialty market.
TABLE 13: TAM / SAM / SOM Bridge Forecast ($Mn)
Market Layer  2025  2027  2030  2035  CAGR / Note
Global Practical TAM  31,800.0  34,262.7  38,319.0  46,174.3  3.8%
Menarini Territory TAM  9,015.0  9,634.0  10,643.6  12,568.4  3.4%
CETP SAM Potential  0.0  1,933.6  6,688.9  6,709.2  Pre-adoption
Menarini SOM Revenue  0.0  10.8  181.7  468.1  Launch-driven

Insight: The Menarini SOM represents approximately 7% of the SAM Potential by 2035, indicating massive headroom for growth if adoption multipliers are triggered by positive PREVAIL outcomes data.1
10.3. Product and Patient Segment Forecast
The transition to FDC-led commercialization is a key structural shift in the forecast.
TABLE 14: Menarini SOM Forecast by Product and Segment ($Mn)
Category  2027  2030  2035  2035 Share
Obicetrapib Mono  10.8  120.3  178.4  38.1%
Obicetrapib FDC  0.0  61.4  289.7  61.9%
ASCVD High-Risk Segment  5.0  83.6  215.3  46.0%
Primary Hyperchol. Seg.  3.0  50.9  131.1  28.0%
HeFH Segment  1.5  25.4  65.5  14.0%

## 11. Europe, UK & Switzerland Opportunity Analysis
11.1. Menarini Rights and Geographic Priorities
TABLE 15: 2035 Country Opportunity Ranking for Menarini
Country  2035 SOM Revenue  2035 Share  Access Readiness  Launch Priority
Germany  142.2  30.4%  High (AMNOG)  1 (Priority)
France  76.4  16.3%  Moderate (HAS)  2 (Priority)
United Kingdom  72.2  15.4%  High (NICE)  2 (Priority)
Italy  52.5  11.2%  Low (Regional)  3 (Selective)
Spain  32.6  7.0%  Low (Budget)  3 (Selective)
Switzerland  17.4  3.7%  High (Premium)  2 (Priority)
Rest of Europe  74.8  16.0%  Variable  3 (Selective)

## 12. Competitive Landscape & Substitute Therapy Pressure
12.1. Direct vs. Indirect Competition
TABLE 16: Therapy Competitive Positioning Matrix
Therapy / Product  Route  Efficacy  Price Tier  Access Burden  Threat Level
Statins / Ezetimibe  Oral  Standard  Low  Very Low  Baseline Ceiling
Bempedoic Acid  Oral  ~18% LDL  Mid  Moderate  Direct Oral Rival
PCSK9 mAbs  Injectable  ~60% LDL  High  High  Substitution Substitute
Inclisiran  Injectable  ~50% LDL  High  High  Long-acting Substitute
Obicetrapib FDC  Oral FDC  ~49% LDL  Mid-Branded  Moderate  Client Asset

## 13. Adoption Dynamics, Access Readiness & Market Conversion
13.1. Converting Approval to Guideline Confidence
TABLE 17: Adoption Readiness Scorecard by Country
Country  Disease Burden  Pricing Potential  Specialist Readiness  Overall Readiness
Germany  5.0  4.0  4.0  4.35 (High)
United Kingdom  4.0  3.0  4.0  3.65 (Medium)
France  4.0  3.0  4.0  3.65 (Medium)
Switzerland  2.0  5.0  4.0  3.65 (Medium)
Italy  4.0  3.0  3.0  3.35 (Low-Med)
Spain  3.0  3.0  3.0  3.00 (Low)

## 14. Menarini Opportunity, Value Capture & Strategic Positioning
14.2. Strategy for Value Capture
TABLE 18: Menarini Strategic Positioning & Levers
Opportunity Area  Menarini Position  Strategic Lever  Priority
HTA Access  Reimbursed Launch  Payer Dossier Development  High
KOL Activation  Specialist Trust  Medical Education / PREVAIL  High
FDC Value  Blended Mon.  Differentiation vs Ezetimibe  High
Wave 1 Markets  Germany / UK  Early Investment Sequencing  High

## 15. Scenario Analysis & Forecast Sensitivities
15.1. Forecast Scenarios (Downside, Base, Upside)
TABLE 19: Market Revenue Scenario Output ($Mn)
Scenario  2030 SOM  2035 SOM  Strategic Meaning
Downside  181.7  468.1  Narrow label / Access restricted
Base  417.5  1,075.3  Expected launch and adoption
Upside  0.0* 0.0* Outcomes-supported acceleration

15.2. Key Sensitivity Drivers
TABLE 20: 2035 SOM Sensitivity Analysis ($Mn)
Variable  Downside Impact  Upside Impact  Strategic Interpretation
Label Breadth  -163.8  +117.0  Priority pre-launch variable
Adoption Rate  -140.4  +140.4  Trust-dependent ramp
Net Price  -140.4  +140.4  HTA negotiation dependent
Access Filter  -117.0  +84.3  Wave 2 timing critical

## 16. Risk Assessment & Mitigation Framework
16.1. Regulatory and Access Risks
TABLE 21: Market Risk Matrix and Mitigation Priority
Risk  Severity  Prob.  Market Impact  Mitigation Priority
Narrow Label  High  Med  Reduces SAM by 40%  High (HTA Dossier)
Class Skepticism  High  Med  Slows Adoption Ramp  High (Med Ed)
Injectable Sub.  Med  High  Caps High-risk share  Med (Oral Positioning)
FDC Delay  Med  Low  Blended Price Drop  Med (MAA Strategy)
Price Pressure  Med  High  Revenue per pt drop  High (HTA Evidence)

## 17. Strategic Roadmap & Future Outlook, 2025–2035
## 18. Appendix
"""

# =============================================================================
# TABLE CONFIG
# =============================================================================
TABLE_COLUMN_COUNTS = {
    1: 5, 2: 5, 3: 5, 4: 5, 5: 6, 6: 5, 7: 5, 8: 5, 9: 5, 10: 5,
    11: 5, 12: 5, 13: 6, 14: 5, 15: 5, 16: 6, 17: 5, 18: 4, 19: 4, 20: 4, 21: 5,
}

# =============================================================================
# TEXT PARSING / MASKING
# =============================================================================
def parse_report_sections(text: str) -> dict:
    sections = {}
    current_header = "Cover / Report Title"
    current_lines = []

    for line in text.strip().splitlines():
        if line.startswith("## "):
            sections[current_header] = "\n".join(current_lines).strip()
            current_header = line.replace("## ", "").strip()
            current_lines = []
        else:
            current_lines.append(line)

    sections[current_header] = "\n".join(current_lines).strip()
    return sections

def remove_source_markers(text: str) -> str:
    """Cleans citation markers without destroying data at the end of lines."""
    cleaned_lines = []
    for line in text.splitlines():
        raw = line.rstrip()
        # Remove standalone leading source definitions (e.g., "1: Model patient...")
        if re.match(r"^\s*\d{1,2}:\s+", raw): continue
        
        # Clean inline citations like ".1" or ".12" at sentence ends
        raw = re.sub(r"(?<=[A-Za-z\)\]])\.(\d{1,2})(?=\s|$)", ".", raw)
        
        # EXTREMELY TARGETED removal of trailing source IDs. 
        # Only removes if it's a space followed by a 1-digit number at the end, 
        # but NOT if it looks like a year, a percentage, or a decimal.
        if not re.search(r"\d+\.\d+$|\d+%$|20\d{2}$", raw):
             raw = re.sub(r"\s+\d{1,2}$", "", raw)

        cleaned_lines.append(raw)
    return "\n".join(cleaned_lines)

def mask_sensitive_numbers(text: str) -> str:
    protected = {}
    def protect(pattern: str):
        nonlocal text
        def repl(match):
            token = f"__SAFE_{len(protected)}__"
            protected[token] = match.group(0)
            return token
        text = re.sub(pattern, repl, text, flags=re.I | re.M)

    # Protect structural entities
    protect(r"\b20\d{2}\s*[–-]\s*20\d{2}\b")
    protect(r"(?m)^\s*\d{1,2}\.\d{1,2}\.?\s+")
    protect(r"\bTABLE\s+\d{1,2}\b")
    protect(r"\b20\d{2}\b")
    protect(r"\bPhase\s+\d\b")
    protect(r"\bWave\s+\d\b")
    protect(r"\bYear\s+\d\b")
    protect(r"\b\d+\s?mg\b")
    protect(r"\bNICE\b|\bEMA\b|\bMHRA\b|\bAMNOG\b|\bHAS\b|\bCEPS\b|\bESC\b|\bEAS\b")

    # Perform masking
    text = re.sub(r"\bUS\s?\d[\d,\.]*\s?(Mn|million|billion|B|M)?", "US$ [Proprietary]", text, flags=re.I)
    text = re.sub(r"US\$?\s?\d[\d,\.]*\s?(Mn|million|billion|B|M)?", "US$ [Proprietary]", text, flags=re.I)
    text = re.sub(r"\$\s?\d[\d,\.]*\s?(Mn|million|billion|B|M|yr|year)?", "$ [Proprietary]", text, flags=re.I)
    text = re.sub(r"\b\d[\d,\.]*\s?%", "[Proprietary]%", text)
    text = re.sub(r"\b\d[\d,\.]*\s?(million|billion|Mn|patients|patient|pts|CAGR)\b", "[Proprietary] \1", text, flags=re.I)
    
    # Mask loose numbers that aren't years or short strings
    text = re.sub(r"\b\d{1,3}(?:,\d{3})+(?:\.\d+)?\b", "[Proprietary]", text)
    text = re.sub(r"(?<![\d\.])\d+\.\d+(?![\d\.])", "[Proprietary]", text)

    for token, value in protected.items():
        text = text.replace(token, value)
    return text

def clean_and_mask(text: str) -> str:
    return mask_sensitive_numbers(remove_source_markers(text))

# =============================================================================
# RENDERING HELPERS
# =============================================================================
def build_table_html(table_title: str, table_lines: list[str]) -> str:
    table_match = re.search(r"TABLE\s+(\d+)", table_title, flags=re.I)
    if not table_match: return ""

    table_num = int(table_match.group(1))
    col_count = TABLE_COLUMN_COUNTS.get(table_num, 5)

    cells = []
    for line in table_lines:
        if not line.strip(): continue
        # Split by 2 or more spaces or tabs to handle columns on the same line
        parts = re.split(r'\s{2,}', line.strip())
        cells.extend(parts)

    if len(cells) < col_count: return ""

    headers = cells[:col_count]
    body = cells[col_count:]

    # Pad body to ensure complete rows
    if len(body) % col_count != 0:
        body = body + [""] * (col_count - (len(body) % col_count))

    header_html = "".join(f"<th>{html.escape(clean_and_mask(h))}</th>" for h in headers)
    rows_html = ""
    for i in range(0, len(body), col_count):
        row = body[i: i+col_count]
        rows_html += "<tr>" + "".join(f"<td>{html.escape(clean_and_mask(c))}</td>" for c in row) + "</tr>"

    return f"""
    <div class="report-table-wrap">
        <div class="report-table-title">{html.escape(clean_and_mask(table_title))}</div>
        <table class="report-table">
            <thead><tr>{header_html}</tr></thead>
            <tbody>{rows_html}</tbody>
        </table>
    </div>
    """

def render_report_block(raw_text: str, stop_before_table=False):
    if not raw_text: return
    lines = raw_text.strip().splitlines()
    output = ["<div class='report-wrapper'>"]
    
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        if not line:
            i += 1
            continue

        if re.match(r"^TABLE\s+\d+:", line, flags=re.I):
            if stop_before_table: break
            table_title = line
            i += 1
            table_lines = []
            while i < len(lines):
                candidate = lines[i].strip()
                if not candidate or candidate.startswith("## ") or re.match(r"^\d{1,2}\.\d{1,2}\.?\s+", candidate) or re.match(r"^TABLE\s+\d+:", candidate, flags=re.I):
                    break
                table_lines.append(candidate)
                i += 1
            output.append(build_table_html(table_title, table_lines))
            continue

        # Subheadings
        if re.match(r"^\d{1,2}\.\d{1,2}\.?\s+", line):
            output.append(f"<div class='report-subheading'>{html.escape(clean_and_mask(line))}</div>")
        else:
            output.append(f"<p class='report-paragraph'>{html.escape(clean_and_mask(line))}</p>")
        i += 1

    output.append("</div>")
    st.markdown("\n".join(output), unsafe_allow_html=True)

# =============================================================================
# CSS / VISUALS
# =============================================================================
def inject_css():
    st.markdown(f"""
        <style>
        .stApp {{ background: {LIGHT_GREY}; color: {DARK_TEXT}; }}
        .block-container {{ max-width: 1300px; padding-top: 2rem; }}
        section[data-testid="stSidebar"] {{ background: linear-gradient(180deg, {BURGUNDY_DARK} 0%, {BURGUNDY} 100%); color: white; }}
        section[data-testid="stSidebar"] * {{ color: white !important; }}
        .hero {{ background: linear-gradient(135deg, {BURGUNDY_DARK} 0%, {BURGUNDY} 100%); color: white; padding: 40px; border-radius: 20px; margin-bottom: 20px; }}
        .hero h1 {{ font-size: 36px; font-weight: 850; margin: 0; }}
        .section-card {{ background: white; border: 1px solid {BORDER_GREY}; border-radius: 15px; padding: 20px; margin-bottom: 15px; }}
        .section-title {{ color: {BURGUNDY}; font-size: 22px; font-weight: 800; }}
        .report-wrapper {{ background: #FBFBFC; border-left: 5px solid {BURGUNDY}; padding: 15px; border-radius: 8px; margin: 10px 0; }}
        .report-subheading {{ color: {BURGUNDY}; font-size: 16px; font-weight: 800; margin-top: 15px; margin-bottom: 5px; }}
        .report-paragraph {{ font-size: 14px; line-height: 1.6; margin-bottom: 10px; }}
        .report-table-wrap {{ margin: 20px 0; border-radius: 10px; overflow: hidden; border: 1px solid {BORDER_GREY}; }}
        .report-table-title {{ background: {BURGUNDY}; color: white; padding: 10px; font-size: 13px; font-weight: 700; }}
        .report-table {{ width: 100%; border-collapse: collapse; font-size: 12px; background: white; }}
        .report-table th {{ background: {BURGUNDY_DARK}; color: white; text-align: left; padding: 10px; }}
        .report-table td {{ padding: 10px; border-bottom: 1px solid {BORDER_GREY}; }}
        .report-table tr:nth-child(even) td {{ background: #f9f9f9; }}
        .stButton > button {{ background: {BURGUNDY} !important; color: white !important; border-radius: 8px; }}
        </style>
    """, unsafe_allow_html=True)

# =============================================================================
# MAIN APP LOGIC
# =============================================================================
REPORT_SECTIONS = parse_report_sections(REPORT_TEXT)

def main():
    inject_css()
    if "logged_in" not in st.session_state: st.session_state["logged_in"] = False

    if not st.session_state["logged_in"]:
        st.markdown("<div style='height:15vh;'></div>", unsafe_allow_html=True)
        col1, col2, col3 = st.columns([1, 1.2, 1])
        with col2:
            st.markdown("<h2 style='text-align:center;'>SMR Client Portal</h2>", unsafe_allow_html=True)
            with st.form("login"):
                u = st.text_input("Username")
                p = st.text_input("Password", type="password")
                if st.form_submit_button("Access Report", use_container_width=True):
                    if u == USERNAME and p == PASSWORD:
                        st.session_state["logged_in"] = True
                        st.rerun()
                    else: st.error("Access Denied")
        return

    with st.sidebar:
        st.title("Report Sections")
        choice = st.radio("Navigation", list(REPORT_SECTIONS.keys()))
        if st.button("Logout"):
            st.session_state["logged_in"] = False
            st.rerun()

    if choice == "Cover / Report Title":
        st.markdown(f"""
            <div class="hero">
                <h1>Global CETP Inhibitors Market Preview</h1>
                <p style="opacity:0.8; margin-top:10px;">Strategic Analysis & 2025–2035 Forecast for Menarini</p>
            </div>
        """, unsafe_allow_html=True)
        st.info("Select a chapter from the sidebar to view the analysis.")
    else:
        st.markdown(f"<div class='section-card'><div class='section-title'>{choice}</div></div>", unsafe_allow_html=True)
        render_report_block(REPORT_SECTIONS[choice])

if __name__ == "__main__":
    main()
