import re
import html
import streamlit as st


# =============================================================================
# PAGE CONFIGURATION
# =============================================================================
st.set_page_config(
    page_title="Global CETP Inhibitors Market Preview | Menarini",
    page_icon="🩺",
    layout="wide",
    initial_sidebar_state="expanded",
)


# =============================================================================
# THEME COLORS
# =============================================================================
BURGUNDY = "#5B0E2D"
BURGUNDY_DARK = "#3A071C"
MID_BURGUNDY = "#8D1645"
SOFT_ROSE = "#D8A7B1"
GOLD = "#C9A227"
LIGHT_GREY = "#F4F5F7"
WHITE = "#FFFFFF"
DARK_TEXT = "#2B2B2B"
MUTED_TEXT = "#666666"
BORDER_GREY = "#E1E4E8"


# =============================================================================
# LOGIN CREDENTIALS
# =============================================================================
USERNAME = "SMR"
PASSWORD = "SMR@2026"


# =============================================================================
# REPORT TEXT
# =============================================================================
REPORT_TEXT = r"""
Global CETP Inhibitors Market, 2025–2035: Obicetrapib-Led Lipid-Lowering Opportunity, TAM/SAM/SOM Buildout & Strategic Positioning for Menarini
## 1. Executive Overview & Strategic Snapshot ($Mn, %, 2025–2035)
1.1. Strategic Market Thesis
The global landscape for lipid-lowering therapies (LLT) is currently undergoing a structural transformation, characterized by the emergence of high-efficacy oral alternatives to established injectable biologics. The cholesteryl ester transfer protein (CETP) inhibitor class, once sidelined due to the historical clinical failures of earlier-generation assets, is being revived through the development of obicetrapib.1 Analysis indicates that the current market represents a unique category-creation opportunity rather than a mature, multi-product space. As of 2025, the strict CETP inhibitor market generates zero commercial revenue, reflecting its pre-approval status.1 However, the commercial potential is anchored in a massive, established lipid-lowering treatment landscape where a significant proportion of high-risk patients fail to achieve low-density lipoprotein cholesterol (LDL-C) goals.1
Obicetrapib is positioned as the first next-generation CETP inhibitor to successfully decouple potent LDL-C lowering from the off-target safety issues and efficacy neutralities that plagued predecessors such as torcetrapib and evacetrapib.1 This asset serves as the primary vehicle for class revival, targeting the LDL-C gap in patients who remain uncontrolled despite maximally tolerated statin therapy.1 The strategic thesis for Menarini focuses on the commercialization of obicetrapib monotherapy and its fixed-dose combination (FDC) with ezetimibe across Europe, the UK, and Switzerland.1 Success is predicated on overcoming historical class skepticism through a robust evidence base, including the pivotal Phase 3 BROADWAY, BROOKLYN, and TANDEM trials, alongside the ongoing PREVAIL cardiovascular outcomes trial (CVOT).1
1.2. Market Size Snapshot
The market sizing architecture differentiates between the currently monetized lipid-lowering landscape, defined as the Practical Total Addressable Market (TAM), and the specific opportunity for CETP inhibitors post-approval, defined as the Serviceable Addressable Market (SAM) and Menarini’s Serviceable Obtainable Market (SOM). The global practical TAM is reset to US$31.8 billion in 2025, reflecting the total revenue generated by existing therapies including statins, ezetimibe, bempedoic acid, PCSK9 monoclonal antibodies, and inclisiran.1
TABLE 1: Executive Market Sizing Summary ($Mn, 2025–2035)
Market Layer
2025 Value
2030 Value
2035 Value
2025–35 CAGR
Global Practical TAM
31,800.0
38,319.0
46,174.3
3.8%
Menarini Territory TAM
9,015.0
10,643.6
12,568.4
3.4%
CETP-Addressable SAM (Revenue Potential)
0.0
6,688.9
6,709.2
Activated 2027
Menarini-Capturable SOM (Revenue)
0.0
181.7
468.1
Launch-driven
Strict CETP Inhibitor Revenue
0.0
181.7
468.1
Launch-driven

Analysis indicates that while the global TAM grows at a steady 3.8%, the Menarini-specific opportunity (SOM) experiences a rapid ramp-up following expected 2027 reimbursement activation, reaching US$468.1 million by 2035.1 The practical TAM reflects the existing "budget pool" for lipid management, while the SAM narrows this to the specific uncontrolled and high-risk patients that obicetrapib will target.1
1.3. Executive Growth Indicators
The trajectory of the CETP inhibitor market is defined by a strategic shift from monotherapy volume to high-value combination treatment. The forecast indicates that while obicetrapib monotherapy will drive early volume in the 2027–2029 period, the obicetrapib/ezetimibe FDC will become the primary revenue driver by the mid-2030s.1
Product Split Evolution: By 2035, the FDC is expected to account for 61.9% of total Menarini SOM revenue, reflecting the clinical trend toward earlier intensification and the convenience of single-pill combinations.1
Geographic Concentration: Menarini’s opportunity is concentrated in Germany, which represents the highest priority market contributing US76.4 million and the UK at US$72.2 million.1
Launch Velocity and Ramp: Revenue generation is strictly launch-flagged, with no commercial revenue projected before 2027. The first full five years of launch (2027–2032) are critical for establishing specialist trust and securing inclusion in clinical guidelines.1
Sensitivity to Outcomes Data: Analysis indicates that positive results from the PREVAIL CVOT trial serve as a major upside lever, potentially increasing adoption multipliers by 15% to 35% above base-case projections in the post-2030 window.1
1.4. Strategic Implications for Menarini
Menarini’s role in this category-creation effort is focused on the successful navigation of European Health Technology Assessment (HTA) and payer landscapes. The opportunity is concentrated in high-risk patient groups, specifically those with Heterozygous Familial Hypercholesterolemia (HeFH) and established Atherosclerotic Cardiovascular Disease (ASCVD) who fail to reach LDL-C targets on standard oral therapies.1
Commercial adoption is expected to depend on the ability to position obicetrapib as a "biologic-like" oral alternative. Menarini must win in the uncontrolled high-risk pool, which represents the primary demand engine for early adoption.3 Priority markets include Germany, the UK, and France, where infrastructure for lipid management is most advanced and the addressable patient pool is largest.1 Strategic efforts must be directed toward medical education that addresses the historical CETP failures by emphasizing obicetrapib’s high selectivity and lack of blood pressure side effects.1 Furthermore, positioning the FDC as a superior oral alternative to bempedoic acid/ezetimibe combinations—leveraging the superior 48.6% LS mean LDL-C reduction observed in the TANDEM trial—will be essential for maximizing blended net price per patient.1
## 2. Market Definition, Scope & TAM/SAM/SOM Architecture
2.1. CETP Inhibitor Market Definition
The CETP inhibitor market is defined as the commercial revenue generated specifically by pharmacological agents designed to inhibit the cholesteryl ester transfer protein to lower LDL-C and reduce major adverse cardiovascular events (MACE). In the 2025–2035 horizon, this is a "near-launch" category represented by obicetrapib.1 The market is distinct from the broader cardiovascular drug market, which includes hypertension and antithrombotic therapies, and is focused exclusively on lipid modification.1
The product scope for this analysis is limited to:
Obicetrapib 10mg Monotherapy: An oral, selective small molecule.2
Obicetrapib 10mg / Ezetimibe 10mg FDC: A fixed-dose combination designed for enhanced LDL-C lowering.7
2.2. Disease Scope and Indications
The addressable population is segmented by clinical risk and the regulatory label expectations set during the EMA and UK submissions. The core indications submitted include the treatment of adults with primary hypercholesterolemia (both HeFH and non-familial) and mixed dyslipidemia.2 Within these groups, the analysis prioritizes:
Secondary Prevention (ASCVD): Patients with established cardiovascular disease requiring aggressive LDL-C targets of <55 mg/dL per 2025 ESC/EAS updates.1
HeFH Patients: A high-risk genetic subgroup where prevalence is approximately 1 in 250 individuals, characterized by significant goal non-attainment.1
Statin-Intolerant Populations: Patients unable to use maximally tolerated statins, representing a key oral non-statin candidate pool.1
2.3. Sizing architecture and Logic
The report employs a strict revenue recognition logic where the category size is $0 until the point of regulatory approval and subsequent reimbursement. This architecture prevents the overlap of CETP revenue with current therapy pools, which are treated as the "Budget TAM."
TABLE 2: Market Layer Architecture & Definitions

Market Layer
Definition
Starts From
Use in Forecast
Relevance to Menarini
Strict CETP Market
Revenue from approved CETP inhibitors only
2027 (Launch)
Core growth metric
Represents client product sales 1
Practical TAM
Current revenue of all relevant lipid-lowering therapies
2025
Ceiling context
Competitive revenue pool 1
SAM
CETP-addressable subset post-label and access filters
2027
Eligible pool
Territory volume potential 1
SOM
Obicetrapib revenue in Menarini territory
2027
Financial forecast
Direct client revenue and profit 1

Analysis indicates that the full cardiovascular drug market is excluded because it contains high-volume, unrelated classes such as beta-blockers and anti-hypertensives. Furthermore, the full dyslipidemia population is not counted as SAM; the filter only includes patients who are diagnosed, treated, and remain above LDL-C targets, as these represent the clinically eligible pool for a premium branded add-on therapy.1
## 3. CETP Mechanism, Class History & Repositioning Logic
3.1. CETP Biology and Mechanism of Action
CETP is a plasma protein that facilitates the exchange of cholesteryl esters from HDL to apoB-containing lipoproteins (VLDL and LDL) in exchange for triglycerides.1 Historically, the industry focused on CETP inhibition as a mechanism to raise HDL-C, the "good cholesterol." However, contemporary clinical logic has shifted toward reducing the atherogenic burden of LDL-C and apoB particles.3 Obicetrapib is a highly selective and potent inhibitor that achieves robust LDL-C reduction at a low 10mg dose, differentiating its pharmacological profile from earlier, less selective molecules.6
3.2. Historical Class Failures and Commercial Lessons
The CETP class has a volatile clinical history that necessitates a strategic rebuilding of physician and payer trust. Analysis of historical assets reveals that failures were largely due to off-target effects or lack of clinical event reduction rather than a failure of the mechanism itself.1
TABLE 3: Historical CETP Asset Comparison & Lessons

Asset
Company
Status
Key Issue / Outcome
Commercial Lesson
Torcetrapib
Pfizer
Discontinued
Off-target toxicity / mortality
Safety is paramount; avoid BP elevation 1
Dalcetrapib
Roche / DalCor
Limited
Efficacy neutrality in broad pool
Potency in LDL-C reduction is required 1
Evacetrapib
Eli Lilly
Discontinued
Failed to show outcomes benefit
Lipid changes must translate to MACE 1
Anacetrapib
Merck
Discontinued
Long half-life / Commercial stop
Launch timing and differentiation matter 1

The clinical trajectory demonstrates that obicetrapib avoids these historical pitfalls by maintaining a neutral blood pressure profile and achieving substantially higher LDL-C reduction (up to ~50% in combination) than predecessors.7
3.3. Category Repositioning Logic
Obicetrapib changes the class narrative by positioning itself as a highly selective oral alternative that bridges the efficacy gap between statins/ezetimibe and injectable biologics.3 To rebuild confidence, the commercial strategy must lead with the "Next-Generation" label, supported by the clean safety profile seen in Phase 3 trials.4 Payer and physician acceptance will depend on the dissemination of the BROADWAY and BROOKLYN data, which show consistent results across diverse populations.1 Outcomes data from the ongoing PREVAIL trial remains strategically vital, as proved cardiovascular benefit is the threshold for broad guideline inclusion and premium reimbursement in the post-statin landscape.1
## 4. Disease Burden & Addressable Patient Pool
4.1. Hypercholesterolemia Prevalence and High-Risk Segments
Cardiovascular disease remains the leading cause of death in the WHO European region, causing over 10,000 deaths per day.14 Circulatory diseases specifically cause 32% of all deaths in the EU.15 Adult populations in core Menarini territories exhibit hypercholesterolemia prevalence rates between 40% and 49%.1 The primary commercial challenge is the "funneling" of this broad population into a reachable, high-risk, uncontrolled patient base.
TABLE 4: Menarini Territory Patient Funnel Analysis (Mn Patients)

Funnel Stage
2025
2030
2035
Interpretation
Adult Population
507.4
508.5
509.7
Total population base across rights territory 1
Diagnosed Patients
161.1
161.8
162.6
Diagnosis rates average 60%–65% 1
Treated Patients
102.3
103.1
103.9
~63% of diagnosed receive treatment 1
Uncontrolled LDL-C
42.1
42.4
42.8
~41% of treated patients fail to hit goals 1
CETP-Relevant Pool
17.5
17.6
17.8
Filtered for high-risk and ASCVD 1
Commercially Reachable
4.4
4.4
4.5
Specialist reach and access narrowed pool 1

Analysis indicates that the "uncontrolled high-risk" pool is the critical demand engine. While the total hypercholesterolemic population is large, the commercially addressable market is narrowed by the requirement for specialist referral and the anticipated HTA restrictions that favor established generic therapies for low-risk patients.1
4.2. Country-Level Demand and Distribution
Demand is highly concentrated in Germany, which maintains the largest uncontrolled LDL-C pool in the territory. Italy and France follow, though their reachable pools are filtered more aggressively by specialist infrastructure and access predictability scores.1
TABLE 5: 2025 Country-Level Demand Engine Summary (Mn Patients)
Country
Diagnosed
Treated
Uncontrolled
CETP-Relevant
Reachable Pool
Germany
24.84
16.89
7.09
3.40
1.02
France
18.98
12.53
5.39
2.53
0.68
United Kingdom
18.29
12.07
5.19
2.39
0.67
Italy
16.14
10.49
4.62
2.12
0.53
Spain
12.03
7.58
3.41
1.53
0.35
Switzerland
2.51
1.75
0.70
0.32
0.10

Analysis demonstrates that Germany’s high treatment rate (68%) and physician infrastructure lead to a reachable pool of over 1 million patients, making it the anchor for the European launch.1 Conversely, while Italy has a large diagnosed population, the specialist reach factor (0.25) significantly reduces the early reachable pool, suggesting a more selective commercial ramp.1
## 5. Current Treatment Landscape & Revenue Pool Benchmark ($Mn)
5.1. The Lipid-Lowering Treatment Pathway
The current lipid-lowering environment is a mature, volume-driven landscape where statins serve as the entrenched first-line therapy. The emergence of non-statin oral add-ons and high-efficacy injectables has created a tiered escalation pathway.
TABLE 6: Current Therapy Class Landscape & Pathway Role

Therapy Class
Route
Role in Pathway
Pricing Tier
Relevance to CETP Entry
Generic Statins
Oral
1st-line standard
Low
Entrenched volume backbone 1
Ezetimibe
Oral
1st-line add-on
Low
Sequencing benchmark; FDC anchor 1
Bempedoic Acid
Oral
Oral non-statin
Branded
Closest branded oral comparator 1
PCSK9 mAbs
Injectable
High-risk escalation
High
High-efficacy benchmark 1
Inclisiran
Injectable
Long-acting specialist
High
Competitor for similar high-risk patients 1

5.2. Practical TAM by Therapy Class ($Mn)
The practical TAM represents the total monetized opportunity within which CETP inhibitors will compete for value share. This US$9 billion territory pool (2025) is dominated by premium injectables, which represent over half of total revenue despite serving a minority of patients.1
TABLE 7: Relevant Treatment TAM by Therapy Class ($Mn)
Therapy Class
2025 Revenue
2030 Revenue
2035 Revenue
CAGR
PCSK9 mAbs
3,065.1
3,618.8
4,273.2
3.4%
Inclisiran
1,442.4
1,702.9
2,010.9
3.4%
Generic Statins
1,622.7
1,915.9
2,262.3
3.4%
Ezetimibe (Add-on)
1,081.8
1,277.2
1,508.2
3.4%
Bempedoic Acid
721.2
851.5
1,005.5
3.4%
Other / Specialty
1,081.8
1,277.2
1,508.2
3.4%
Territory Total
9,015.0
10,643.6
12,568.4
3.4%

Insight: The dominance of the injectable biologics segment (PCSK9/Inclisiran) sets a high-efficacy ceiling for the market. If obicetrapib can demonstrate similar MACE reduction with oral convenience, it can potentially substitute value from this ~$6.3 billion pool by 2035.4 The growth of bempedoic acid (10.5% CAGR in secondary research estimates) further validates the market’s willingness to pay for branded oral non-statins.1
5.3. Practical TAM by Geography and Segment
Germany represents the largest geographic revenue pool, accounting for US$1.65 billion in 2025 practical TAM.1 From a patient segment perspective, the ASCVD uncontrolled pool is the highest-value segment, representing 46% of the territory's treatment revenue.1
TABLE 8: Menarini Territory Practical TAM by Patient Segment ($Mn)

Patient Segment
2025
2030
2035
Interpretation
ASCVD / High-Risk
4,146.9
4,896.1
5,781.4
Priority intensification segment 1
Hypercholesterolemia
2,524.2
2,980.2
3,519.1
Main label-relevant pool 1
HeFH
1,262.1
1,490.1
1,759.6
High-unmet need specialty group 1
Mixed Dyslipidemia
811.4
957.9
1,131.2
Adjacent label-expansion pool 1
Statin Intolerant
270.5
319.3
377.1
Critical oral non-statin niche 1

Demand is driven by the tightening of ESC/EAS guidelines, which favor earlier combination therapy to reach target LDL-C levels below 1.8 mmol/L and 1.4 mmol/L.8 This clinical trend supports the positioning of the obicetrapib/ezetimibe FDC as an early escalation option.16
## 6. Unmet Need, LDL-C Control Gap & SAM Conversion
6.1. The LDL-C Control Gap in Europe
Despite the availability of generic and branded therapies, LDL-C goal attainment remains suboptimal across Europe. Data from the DA VINCI study indicate that only 31.1% of high and very-high risk patients achieve risk-based targets.4 This non-attainment is driven by:
Statin Resistance and Intolerance: Approximately 10% of high-risk patients are statin-intolerant or require non-statin add-ons to reach goal.1
Injection Burden: A significant portion of the patient and prescriber base is resistant to self-injection or the cold-chain logistics required for PCSK9 monoclonal antibodies.3
Treatment Intensification Gaps: Clinical inertia often prevents the escalation to high-efficacy therapies, creating a pool of "undertreated" high-risk individuals.7
6.2. SAM Conversion Logic
The SAM represents the addressable "commercial ceiling" after filtering the theoretical patient pool by expected labeling and payer access hurdles. The model converts the uncontrolled LDL-C pool into SAM based on a base eligibility factor (0.82) and a reachability factor (1.0) in the base case.1
TABLE 9: TAM-to-SAM Revenue Potential Bridge ($Mn, 2035)

Step
Pool / Revenue
Conversion
Output
Rationale
Practical TAM
$12,568.4
N/A
$12,568.4
Total territory relevant LLT pool 1
Uncontrolled Filter
$12,568.4
42.1%
$5,291.3
Targets only those failing goals 1
Label / Access
$5,291.3
82.0%
$4,338.9
Filtered for label and HTA 1
SAM Potential
$6,709.2
Formula-derived
$6,709.2
Calculated pre-adoption ceiling 1

Analysis indicates that the SAM Potential is not the actual revenue, but the pre-adoption revenue ceiling. Revenue only begins to flow once country launch flags are activated, ensuring consistency with the model’s "zero revenue pre-approval" rule.1
6.3. Label Eligibility by Segment
The breadth of the approved label will be the single most important variable for early SAM activation. The model segments eligibility based on clinical risk categories.
HeFH (Base 0.75 Factor): High priority specialist segment with the strongest medical evidence for reimbursement.1
ASCVD (Base 0.55 Factor): The largest intensification pool, but subject to stricter payer filters until CV outcomes data is fully integrated.1
Statin-Intolerant (Base 0.60 Factor): Oral non-statin positioning supports a higher eligibility factor in this niche.1
## 7. Obicetrapib Clinical Evidence & Pipeline Positioning
7.1. Obicetrapib Asset Profile
Obicetrapib is a next-generation CETP inhibitor developed to overcome the potency and safety limitations of earlier class assets. Clinical evidence from Phase 2 and 3 programs demonstrates that obicetrapib, both as monotherapy and in combination with ezetimibe, achieves biologic-like LDL-C reduction through an oral mechanism.4
TABLE 10: Obicetrapib Pivotal Trial Evidence Summary

Trial
Phase
Population
Result
Commercial Implication
BROADWAY
Phase 3
ASCVD / HeFH
~35% LDL-C reduction
Supports base lipid label 2
BROOKLYN
Phase 3
HeFH
36.3% reduction (adj.)
Specialist segment validator 1
TANDEM
Phase 3
High-risk/ASCVD
48.6% LS mean reduction
Driver for FDC positioning 1
ROSE2
Phase 2
LLT-treated
59% Median reduction
Benchmarks efficacy vs biologics 9
PREVAIL
Phase 3
ASCVD / High-risk
Ongoing (9,500 pts)
Long-term adoption accelerator 1

7.2. Safety and Differentiation
Historical CETP class concerns focused on off-target hypertensive effects (torcetrapib) and lack of potency in broad populations (dalcetrapib).1 Analysis indicates that obicetrapib maintains a safety profile comparable to placebo, with no observed impact on blood pressure.4 This differentiation is critical for securing clinical confidence. Furthermore, obicetrapib’s high selectivity for CETP over other lipid-transfer proteins reduces the risk of non-specific lipid changes.3
7.3. Pipeline and Expansion Potential
The RUBENS program, initiated in December 2025, evaluates obicetrapib in type 2 diabetes and metabolic syndrome, populations that require aggressive lipid lowering but often face barriers to intensification.5 Success in RUBENS could expand the SAM in the post-2030 period. Additionally, exploratory analyses from the BROADWAY trial indicate a potential link between CETP inhibition and neurodegeneration biomarkers (p-tau217), presenting a long-term "narrative optionality" in Alzheimer’s disease that is not currently included in the core lipid market sizing.1
## 8. Regulatory Pathway, Label Scenarios & Launch Timing
8.1. Regulatory Submission and Status
In August 2025, the EMA validated the Marketing Authorisation Applications (MAAs) for both obicetrapib monotherapy and the obicetrapib/ezetimibe FDC.2 Parallel submissions were accepted by the MHRA (UK) and Swissmedic.5 Approval decisions are anticipated in the second half of 2026, positioning 2027 as the first full commercial revenue year.5
8.2. Country Launch Waves and Activation
Launch activation is staggered across the Menarini territory based on country-specific reimbursement pathways and HTA evidence requirements.
TABLE 11: Menarini Territory Launch Sequencing & Access Logic

Country
Reimbursement
Launch Wave
Access Pathway Logic
Access Risk
Germany
2027
Wave 1
AMNOG early reimbursed launch
Moderate 1
United Kingdom
2027
Wave 1
NICE cost-effectiveness hurdle
High 1
France
2028
Wave 2
HAS/CEPS price-volume control
Moderate 1
Switzerland
2028
Wave 2
Premium market specialty access
Low 1
Italy
2028
Wave 2
Regional implementation variation
High 1
Spain
2028
Wave 2
Budget pressure/regional delays
High 1

The model assumes that revenue starts strictly from the reimbursement year. Germany and the UK are prioritized due to their established infrastructure for specialist-led early access. WAVE 2 countries follow once national pricing negotiations are finalized.1
8.3. The Influence of Cardiovascular Outcomes Data
The adoption ramp follows a standard pharmaceutical S-curve, reaching peak penetration approximately 8 years after launch.1 However, the readout of the PREVAIL CVOT trial serves as a critical strategic milestone. Analysis indicates that positive cardiovascular benefit results could transform obicetrapib from a "specialist add-on" to a "standard intensification" therapy, materially increasing adoption rates in the 2031–2035 period.1
## 9. Pricing, Reimbursement & Monetization Architecture ($/Patient/Year)
9.1. Pricing Methodology for Pre-Approval Asset
Obicetrapib is priced as a premium branded oral therapy. Analysis indicates that the pricing strategy must navigate the space between low-cost generic ezetimibe and high-cost injectable biologics. The "mid-branded" pricing tier is anchored to bempedoic acid (Nustendi/Nilemdo), which serves as the closest oral benchmark.1
TABLE 12: Country Net Pricing and Gross-to-Net (GTN) Assumptions

Country
Mono Net Price
FDC Net Price
GTN Factor
Pricing Rationale
Germany
$1,050
$1,312.5
0.72
AMNOG mid-branded benchmark 1
Switzerland
$1,200
$1,500.0
0.75
Premium market capability 1
France
$900
$1,125.0
0.68
HAS/CEPS mid-tier proxy 1
United Kingdom
$875
$1,093.8
0.70
NICE cost-effectiveness floor 1
Italy
$850
$1,062.5
0.66
Regional implementation pressure 1
Spain
$800
$1,000.0
0.65
Budget-conscious benchmark 1

FDC Premium: The FDC includes a 25% price premium over monotherapy, justified by the dual-mechanism efficacy and improved patient adherence.1
9.2. Monetization Formula and Revenue Per Patient
The monetization model accounts for annual price erosion to avoid unrealistic long-term revenue projections. Erosion factors range from 1.2% in core markets to 1.8% in the "Rest of Europe," reflecting standard HTA price reviews and generic entry in adjacent lipid classes.1
Gross-to-Net Adjustments: GTN factors between 25% and 38% reflect the impact of statutory rebates and national/regional negotiated discounts.1
Blended Monetization: As the product mix shifts from monotherapy to FDC (projected 61.9% share by 2035), the blended net revenue per patient is expected to rise despite mono price erosion.1
9.3. HTA Evidence and Payer Requirements
Payer access will depend on the demonstration of incremental benefit over generic ezetimibe and branded bempedoic acid. NICE (UK) and HAS (France) are expected to scrutinize the TANDEM trial data, which achieved a 48.6% LDL-C reduction—significantly higher than the ~18% reduction typically associated with bempedoic acid.12 Proactive health-economic modeling is required to position the FDC as a "pre-injectable" step that avoids the higher budgetary burden of PCSK9/inclisiran therapies.1
## 10. Market Size & Forecast, 2025–2035 ($Mn, Patients, %)
10.1. Forecast Methodology
The forecast methodology utilizes a bottom-up patient demand engine.1 Addressable SAM patients are converted into treated SOM patients based on a gradual adoption ramp (0.5% Year 0 to 9.5% at peak) to reflect the medical education requirements for a revived class.1 Revenue is calculated as treated patients multiplied by the blended net annual price of obicetrapib mono and FDC.1
10.2. Market Layer Forecast ($Mn)
The market demonstrates a rapid category-creation ramp following the 2027 launch wave. While the underlying lipid TAM remains stable, the CETP category builds from zero to a significant specialty market.
TABLE 13: TAM / SAM / SOM Bridge Forecast ($Mn)
Market Layer
2025
2027
2030
2035
CAGR / Note
Global Practical TAM
31,800.0
34,262.7
38,319.0
46,174.3
3.8% (2025–35)
Menarini Territory TAM
9,015.0
9,634.0
10,643.6
12,568.4
3.4% (2025–35)
CETP SAM Potential
0.0
1,933.6
6,688.9
6,709.2
Pre-adoption ceiling
Menarini SOM Revenue
0.0
10.8
181.7
468.1
Launch-driven ramp

Insight: The Menarini SOM represents approximately 7% of the SAM Potential by 2035, indicating massive headroom for growth if adoption multipliers are triggered by positive PREVAIL outcomes data.1
10.3. Product and Patient Segment Forecast
The transition to FDC-led commercialization is a key structural shift in the forecast.
TABLE 14: Menarini SOM Forecast by Product and Segment ($Mn)

Category
2027
2030
2035
2035 Share
Obicetrapib Mono
10.8
120.3
178.4
38.1% 1
Obicetrapib FDC
0.0
61.4
289.7
61.9% 1
ASCVD High-Risk Segment
5.0
83.6
215.3
46.0% 1
Primary Hyperchol. Seg.
3.0
50.9
131.1
28.0% 1
HeFH Segment
1.5
25.4
65.5
14.0% 1

Demand is driven by the ASCVD and primary hypercholesterolemia pools, which together account for 74% of the total revenue.1 The HeFH segment, while smaller in volume, serves as a high-margin entry point for specialist-led early adoption.1
## 11. Europe, UK & Switzerland Opportunity Analysis
11.1. Menarini Rights and Geographic Priorities
Menarini holds exclusive rights across Europe, the UK, and Switzerland.7 The territory accounts for 28.3% of the global practical lipid TAM in 2025, but this share is expected to moderate to 19.5% by 2035 as non-rights markets (US/Asia) experience faster therapy intensification.1
TABLE 15: 2035 Country Opportunity Ranking for Menarini

Country
2035 SOM Revenue
2035 Share
Access Readiness
Launch Priority
Germany
$142.2 Mn
30.4%
High (AMNOG)
1 (Priority) 1
France
$76.4 Mn
16.3%
Moderate (HAS)
2 (Priority) 1
United Kingdom
$72.2 Mn
15.4%
High (NICE)
2 (Priority) 1
Italy
$52.5 Mn
11.2%
Low (Regional)
3 (Selective) 1
Spain
$32.6 Mn
7.0%
Low (Budget)
3 (Selective) 1
Switzerland
$17.4 Mn
3.7%
High (Premium)
2 (Priority) 1
Rest of Europe
$74.8 Mn
16.0%
Variable
3 (Selective) 1

Germany and the UK drive early value due to their 2027 reimbursement activation.1 France and Switzerland contribute significantly to mid-term growth, with Switzerland offering the highest net price potential ($1,200/yr) albeit with a smaller volume.1
11.2. Strategic Interpretation for Menarini
Analysis indicates that commercial success is contingent on a two-pronged strategy:
Wave 1 Intensity (2027): Focus resources on Germany and the UK to establish a foothold in the HeFH and high-risk ASCVD specialist markets.1
Wave 2 Expansion (2028–2030): Leverage initial success and broader lipid goal non-attainment data to secure reimbursement in France, Italy, and Spain.1 Proactive management of regional Implementation in Italy and Spain is required to avoid adoption bottlenecks.1
## 12. Competitive Landscape & Substitute Therapy Pressure
12.1. Direct vs. Indirect Competition
Direct competition within the CETP class is non-existent for the current forecast period, providing obicetrapib with a first-mover advantage.1 However, indirect competition from other lipid-lowering classes is the primary determinant of adoption ceilings.
TABLE 16: Therapy Competitive Positioning Matrix

Therapy / Product
Route
Efficacy
Price Tier
Access Burden
Threat Level
Statins / Ezetimibe
Oral
Standard
Low
Very Low
Baseline Ceiling 1
Bempedoic Acid
Oral
~18% LDL
Mid
Moderate
Direct Oral Rival 1
PCSK9 mAbs
Injectable
~60% LDL
High
High
Substitution Substitute 1
Inclisiran
Injectable
~50% LDL
High
High
Long-acting Substitute 1
Obicetrapib FDC
Oral FDC
~49% LDL
Mid-Branded
Moderate
Client Asset 18

12.2. Positioning Against Substitute Therapies
Obicetrapib’s success depends on carving out a space between generic add-ons and expensive biologics.
Convenience Advantage: Analysis indicates that oral small molecules avoid the "injection barrier" and cold-chain logistics of biologics.3
Efficacy vs. Bempedoic Acid: Obicetrapib (35%–49% reduction) significantly outperforms bempedoic acid (~18%), providing a clear efficacy narrative for HTA dossiers.12
Access Differentiator: Position the FDC as a "biologic-like" oral step that provides near-PCSK9 levels of LDL-C lowering at a lower budgetary impact to payers.1
12.3. Emerging and Future Threats
Long-term threats include the maturation of Lp(a) therapies and RNA-based treatments for ANGPTL3 and apoC-III.1 While these target different lipid pathways, they compete for the same high-risk cardiovascular patients and specialist budget allocations. Menarini should monitor these developments but prioritize obicetrapib’s established oral-add-on positioning in the near-term.1
## 13. Adoption Dynamics, Access Readiness & Market Conversion
13.1. Converting Approval to Guideline Confidence
The conversion from regulatory approval to routine prescribing requires a transition through four stages of readiness.
TABLE 17: Adoption Readiness Scorecard by Country

Country
Disease Burden
Pricing Potential
Specialist Readiness
Overall Readiness
Germany
5.0
4.0
4.0
4.35 (High) 1
United Kingdom
4.0
3.0
4.0
3.65 (Medium) 1
France
4.0
3.0
4.0
3.65 (Medium) 1
Switzerland
2.0
5.0
4.0
3.65 (Medium) 1
Italy
4.0
3.0
3.0
3.35 (Low-Med) 1
Spain
3.0
3.0
3.0
3.00 (Low) 1

13.2. Specialist and Payer Barriers
Adoption is initially restricted to cardiologists and lipidologists due to the historical CETP skepticism.1 Primary care adoption is expected only after obicetrapib is incorporated into broad clinical guidelines (ESC/EAS) and proves its safety in a real-world setting.1 Payer barriers include step-therapy requirements—where patients may be forced to fail ezetimibe or bempedoic acid—and restrictive HTA criteria for ASCVD patients without HeFH.1
13.3. Adoption Ramp and Mix Dynamics
The adoption ramp follows a steady progression. Analysis indicates that Year 0 launch year penetration is a conservative 0.5% of SAM, growing to 6.5% by Year 5 and 9.5% by the end of the forecast period.1 The product mix is expected to flip in 2033, with the FDC becoming the dominant revenue driver as payers and physicians prioritize dual-mechanism simplification.1
## 14. Menarini Opportunity, Value Capture & Strategic Positioning
14.1. Menarini SOM and Gross Profit Proxy
The Menarini-capturable opportunity is estimated to grow to a US374.5 million (approximately 80% margin proxy) by 2035.1
TABLE 18: Menarini Strategic Positioning & Levers

Opportunity Area
Menarini Position
Strategic Lever
Priority
HTA Access
Reimbursed Launch
Payer Dossier Development
High 1
KOL Activation
Specialist Trust
Medical Education / PREVAIL
High 1
FDC Value
Blended Mon.
Differentiation vs Ezetimibe
High 1
Wave 1 Markets
Germany / UK
Early Investment Sequencing
High 1
Expansion Pool
ASCVD Adoption
Real-World Evidence Plan
Medium 1

14.2. Strategy for Value Capture
Menarini’s strategy centers on positioning obicetrapib as the "Oral Biologic" equivalent.
Specialist Reach: Leverage existing cardiovascular capabilities to target the ~4.4 million reachable high-risk patients.1
HTA Dossiers: Use the TANDEM data to secure early AMNOG and NICE approvals. Emphasize the potential for obicetrapib to reduce the overall "budget impact" by delaying the need for higher-cost injectables.1
Medical Education: Proactively address the CETP class skepticism by leading with selectivity and potency data.1
## 15. Scenario Analysis & Forecast Sensitivities
15.1. Forecast Scenarios (Downside, Base, Upside)
The forecast is subject to significant uncertainty regarding regulatory labeling and HTA acceptance.
TABLE 19: Market Revenue Scenario Output ($Mn)

Scenario
2030 SOM
2035 SOM
Strategic Meaning
Downside
$181.7
$468.1
Narrow label / Access restricted 1
Base
$417.5
$1,075.3
Expected launch and adoption 1
Upside
$0.0*
$0.0*
Outcomes-supported acceleration

Note: Base revenue of $417.5M in 2030 represents the standard launch path, while the Downside case accounts for 1-year delays and price pressure.1
15.2. Key Sensitivity Drivers
Revenue is most sensitive to the label eligibility multiplier and adoption rates.
TABLE 20: 2035 SOM Sensitivity Analysis ($Mn)

Variable
Downside Impact
Upside Impact
Strategic Interpretation
Label Breadth
-US$163.8
+US$117.0
Priority pre-launch variable 1
Adoption Rate
-US$140.4
+US$140.4
Trust-dependent ramp 1
Net Price
-US$140.4
+US$140.4
HTA negotiation dependent 1
Access Filter
-US$117.0
+US$84.3
Wave 2 timing critical 1
FDC Mix
-US$46.8
+US$56.2
Mix shift impacts blended price 1

Interpretation: A narrow high-risk label would reduce the potential territory revenue by over 35%, emphasizing the need for a broad label strategy at EMA.1 Conversely, positive outcomes results could expand the multiplier by 45%.1
## 16. Risk Assessment & Mitigation Framework
16.1. Regulatory and Access Risks
The primary threat to the Menarini SOM is a restrictive reimbursement environment or delay in regulatory decisions.
TABLE 21: Market Risk Matrix and Mitigation Priority

Risk
Severity
Prob.
Market Impact
Mitigation Priority
Narrow Label
High
Med
Reduces SAM by 40%
High (HTA Dossier) 1
Class Skepticism
High
Med
Slows Adoption Ramp
High (Med Ed) 1
Injectable Sub.
Med
High
Caps High-risk share
Med (Oral Positioning) 1
FDC Delay
Med
Low
Blended Price Drop
Med (MAA Strategy) 1
Price Pressure
Med
High
Revenue per pt drop
High (HTA Evidence) 1

The most immediate priority is differentiating obicetrapib safety to address the historical failures. Menarini must proactively manage the "legacy CETP" narrative in cardiologist peer groups.1
## 17. Strategic Roadmap & Future Outlook, 2025–2035
17.1. Launch Preparation and Wave 1 Execution (2025–2027)
Analysis indicates the focus must be on 2H 2026 approval and 2027 Wave 1 launch in Germany, the UK, and Switzerland.5 Menarini must finalize its HTA dossier, highlighting the 48.6% LDL-C reduction in the TANDEM trial to justify its premium oral status.18
17.2. Scaling and Guideline Integration (2028–2030)
The mid-period focus shifts to securing reimbursement in Wave 2 markets (France, Italy, Spain) and scaling the FDC product mix to ~29% of total patients.1 Success depends on moving obicetrapib from a "specialist curios" to a "standard escalation option" for patients above targets.1
17.3. Outcomes Maturity and Broad Adoption (2031–2035)
Post-PREVAIL data, the commercial narrative will transition from LDL-C lowering to MACE reduction benefit. This phase is characterized by the potential expansion into broader cardiometabolic populations and the maturation of the FDC as the territory’s dominant oral intensification therapy, reaching a US$468.1 million revenue maturity.1
## 18. Appendix
18.1. Calculation Logic and Assumptions
TAM Formula: Σ (Country Practical TAM) = Σ (Current Relevant LLT Revenue Pools).1
SAM Patients Formula: (Adult Pop. × Hyperchol. Prev. × Uncontrolled LDL-C rate) × (Label Eligibility Factor × Reachability Factor).1
Monetization Formula: (Treated Patients × Mono Mix × Mono Net Price) + (Treated Patients × FDC Mix × FDC Net Price).1
Price Erosion: A standard -1.2% CAGR applied to annual net prices across core territories.1
Adoption Ramp: Year 0: 0.005; Year 5: 0.065; Year 8: 0.095.1
18.2. Source Registry (Top Tranche)
2: Regulatory status and EMA submission details.
1: Model patient funnel and epidemiology benchmarks.
1: Pricing engine and annual forecast outputs.
1: Menarini territory analysis and scenario dashboard.
1: Workbook extractions for clinical evidence and strategy.
18.3. Glossary of Terms
ASCVD: Atherosclerotic Cardiovascular Disease.
CETP: Cholesteryl Ester Transfer Protein.
FDC: Fixed-Dose Combination.
HeFH: Heterozygous Familial Hypercholesterolemia.
HTA: Health Technology Assessment.
MACE: Major Adverse Cardiovascular Events.
SOM: Serviceable Obtainable Market (Menarini capture).
Final Strategic Outlook: Analysis indicates that the CETP category revival through obicetrapib offers Menarini a sustainable, high-value specialty revenue stream. By leveraging the superior potency of the FDC, prioritizing the German and UK launch waves, and rebuilding specialist trust through evidence-based outcomes positioning, Menarini can establish itself as the dominant leader in the next generation of oral lipid-lowering therapies.1
"""


# =============================================================================
# TABLE CONFIG
# =============================================================================
TABLE_COLUMN_COUNTS = {
    1: 5,
    2: 5,
    3: 5,
    4: 5,
    5: 6,
    6: 5,
    7: 5,
    8: 5,
    9: 5,
    10: 5,
    11: 5,
    12: 5,
    13: 6,
    14: 5,
    15: 5,
    16: 6,
    17: 5,
    18: 4,
    19: 4,
    20: 4,
    21: 5,
}


# =============================================================================
# TEXT PARSING / MASKING
# =============================================================================
def parse_report_sections(text: str) -> dict:
    sections = {}
    current_header = "Cover / Report Title"
    current_lines = []

    for line in text.strip().splitlines():
        if line.startswith("## "):
            sections[current_header] = "\n".join(current_lines).strip()
            current_header = line.replace("## ", "").strip()
            current_lines = []
        else:
            current_lines.append(line)

    sections[current_header] = "\n".join(current_lines).strip()
    return sections


def remove_source_markers(text: str) -> str:
    cleaned_lines = []

    for line in text.splitlines():
        raw = line.rstrip()

        if re.match(r"^\s*\d{1,2}:\s+", raw):
            continue

        raw = re.sub(r"(?<=[A-Za-z\)\]])\.(\d{1,2})(?=\s|$)", ".", raw)
        raw = re.sub(r"(?<=%)\s+\d{1,2}$", "", raw)

        protected_line = (
            re.match(r"^\s*TABLE\s+\d+", raw, flags=re.I)
            or re.match(r"^\s*\d{1,2}\.\d{1,2}", raw)
            or re.match(r"^\s*Phase\s+\d", raw, flags=re.I)
            or re.match(r"^\s*Wave\s+\d", raw, flags=re.I)
            or re.match(r"^\s*Year\s+\d", raw, flags=re.I)
        )

        if not protected_line:
            raw = re.sub(r"(?<=[A-Za-z\)\]])\s+\d{1,2}$", "", raw)

        cleaned_lines.append(raw)

    return "\n".join(cleaned_lines)


def mask_sensitive_numbers(text: str) -> str:
    protected = {}

    def protect(pattern: str):
        nonlocal text

        def repl(match):
            token = f"__SAFE_{len(protected)}__"
            protected[token] = match.group(0)
            return token

        text = re.sub(pattern, repl, text, flags=re.I | re.M)

    protect(r"\b20\d{2}\s*[–-]\s*20\d{2}\b")
    protect(r"\b20\d{2}\s*[–-]\s*\d{2}\b")
    protect(r"(?m)^\s*\d{1,2}\.\d{1,2}\.?\s+")
    protect(r"\bTABLE\s+\d{1,2}\b")
    protect(r"\b20\d{2}\b")
    protect(r"\bPhase\s+\d[a-zA-Z]?\b")
    protect(r"\bWave\s+\d\b")
    protect(r"\bYear\s+\d\b")
    protect(r"\b\d+\s?mg\b")
    protect(r"\b\d+(st|nd|rd|th)-line\b")
    protect(r"\bNICE\b|\bEMA\b|\bMHRA\b|\bAMNOG\b|\bHAS\b|\bCEPS\b|\bESC\b|\bEAS\b")

    text = re.sub(r"\bUS\s?\d[\d,\.]*\s?(Mn|million|billion|B|M)?", "US$ [Proprietary]", text, flags=re.I)
    text = re.sub(r"US\$?\s?\d[\d,\.]*\s?(Mn|million|billion|B|M)?", "US$ [Proprietary]", text, flags=re.I)
    text = re.sub(r"\$\s?\d[\d,\.]*\s?(Mn|million|billion|B|M|yr|year)?", "$ [Proprietary]", text, flags=re.I)
    text = re.sub(r"\b\d[\d,\.]*\s?%", "[Proprietary]%", text)
    text = re.sub(
        r"\b\d[\d,\.]*\s?(million|billion|Mn|patients|patient|pts|CAGR)\b",
        r"[Proprietary] \1",
        text,
        flags=re.I,
    )
    text = re.sub(r"\b\d{1,3}(?:,\d{3})+(?:\.\d+)?\b", "[Proprietary]", text)
    text = re.sub(r"\b\d+\.\d+\b", "[Proprietary]", text)
    text = re.sub(r"\b(?!(?:19|20)\d{2}\b)\d{4,}\b", "[Proprietary]", text)

    for token, value in protected.items():
        text = text.replace(token, value)

    return text


def clean_and_mask(text: str) -> str:
    return mask_sensitive_numbers(remove_source_markers(text))


REPORT_SECTIONS = parse_report_sections(REPORT_TEXT)


def get_section(chapter_number: int, fallback_keyword: str = "") -> str:
    chapter_prefix = f"{chapter_number}."

    for title, content in REPORT_SECTIONS.items():
        if title.strip().startswith(chapter_prefix):
            return content

    if fallback_keyword:
        for title, content in REPORT_SECTIONS.items():
            if fallback_keyword.lower() in title.lower():
                return content

    return ""


# =============================================================================
# CSS
# =============================================================================
def inject_css():
    st.markdown(
        f"""
        <style>
        .stApp {{
            background: {LIGHT_GREY};
            color: {DARK_TEXT};
        }}

        [data-testid="stHeader"] {{
            background: rgba(244,245,247,0.72);
        }}

        footer {{
            visibility: hidden;
        }}

        .block-container {{
            max-width: 1380px;
            padding-top: 1.2rem;
            padding-bottom: 1rem;
        }}

        section[data-testid="stSidebar"] {{
            background: linear-gradient(180deg, {BURGUNDY_DARK} 0%, {BURGUNDY} 100%);
        }}

        section[data-testid="stSidebar"] * {{
            color: white;
        }}

        .hero {{
            background: linear-gradient(135deg, {BURGUNDY_DARK} 0%, {BURGUNDY} 45%, {MID_BURGUNDY} 100%);
            color: white;
            padding: 48px;
            border-radius: 28px;
            box-shadow: 0 20px 55px rgba(58,7,28,0.22);
            margin-bottom: 24px;
        }}

        .hero-kicker {{
            display: inline-block;
            background: rgba(201,162,39,0.18);
            color: {GOLD};
            border: 1px solid rgba(201,162,39,0.45);
            padding: 6px 12px;
            border-radius: 999px;
            font-size: 12px;
            font-weight: 800;
            letter-spacing: 0.08em;
            text-transform: uppercase;
            margin-bottom: 18px;
        }}

        .hero h1 {{
            font-size: 42px;
            line-height: 1.08;
            font-weight: 850;
            margin: 0 0 14px 0;
            letter-spacing: -0.03em;
        }}

        .hero h2 {{
            color: {SOFT_ROSE};
            font-size: 19px;
            font-weight: 500;
            margin: 0 0 22px 0;
            max-width: 980px;
        }}

        .hero p {{
            max-width: 930px;
            font-size: 15px;
            line-height: 1.7;
            color: rgba(255,255,255,0.88);
        }}

        .kpi-grid {{
            display: grid;
            grid-template-columns: repeat(3, minmax(0, 1fr));
            gap: 16px;
            margin: 18px 0 28px 0;
        }}

        .kpi-card {{
            background: {WHITE};
            border: 1px solid {BORDER_GREY};
            border-radius: 18px;
            padding: 20px;
            min-height: 132px;
            box-shadow: 0 10px 30px rgba(43,43,43,0.045);
        }}

        .kpi-label {{
            color: {MUTED_TEXT};
            font-size: 12px;
            font-weight: 800;
            letter-spacing: 0.05em;
            text-transform: uppercase;
            margin-bottom: 10px;
        }}

        .kpi-value {{
            color: {BURGUNDY};
            font-size: 25px;
            line-height: 1.15;
            font-weight: 850;
            margin-bottom: 10px;
        }}

        .kpi-note {{
            color: {MUTED_TEXT};
            font-size: 13px;
            line-height: 1.45;
        }}

        .section-card {{
            background: {WHITE};
            border: 1px solid {BORDER_GREY};
            border-radius: 22px;
            padding: 26px 28px;
            box-shadow: 0 10px 34px rgba(43,43,43,0.045);
            margin-bottom: 22px;
        }}

        .section-title {{
            color: {BURGUNDY_DARK};
            font-size: 25px;
            font-weight: 850;
            letter-spacing: -0.02em;
            margin: 0 0 12px 0;
        }}

        .section-subtitle {{
            color: {MUTED_TEXT};
            font-size: 14px;
            line-height: 1.65;
            margin-bottom: 16px;
        }}

        .report-wrapper {{
            background: #FBFBFC;
            border: 1px solid {BORDER_GREY};
            border-left: 5px solid {BURGUNDY};
            border-radius: 16px;
            padding: 18px 20px;
            margin: 14px 0 22px 0;
        }}

        .report-subheading {{
            color: {BURGUNDY};
            font-size: 17px;
            font-weight: 850;
            margin: 20px 0 10px 0;
        }}

        .report-paragraph {{
            color: {DARK_TEXT};
            font-size: 14.5px;
            line-height: 1.72;
            margin: 0 0 12px 0;
        }}

        .report-table-wrap {{
            background: {WHITE};
            border: 1px solid {BORDER_GREY};
            border-radius: 16px;
            margin: 18px 0 24px 0;
            overflow-x: auto;
            box-shadow: 0 8px 24px rgba(43,43,43,0.045);
        }}

        .report-table-title {{
            background: linear-gradient(135deg, {BURGUNDY} 0%, {MID_BURGUNDY} 100%);
            color: {WHITE};
            font-size: 14px;
            font-weight: 850;
            padding: 13px 16px;
        }}

        .report-table {{
            width: 100%;
            border-collapse: collapse;
            min-width: 760px;
            font-size: 13px;
        }}

        .report-table th {{
            background: {BURGUNDY_DARK};
            color: {WHITE};
            text-align: left;
            padding: 12px 14px;
            font-weight: 800;
            border-right: 1px solid rgba(255,255,255,0.12);
            vertical-align: top;
        }}

        .report-table td {{
            padding: 12px 14px;
            border-bottom: 1px solid {BORDER_GREY};
            color: {DARK_TEXT};
            vertical-align: top;
            line-height: 1.45;
        }}

        .report-table tbody tr:nth-child(even) td {{
            background: #F8F8FA;
        }}

        .chart-card {{
            background: {WHITE};
            border: 1px solid {BORDER_GREY};
            border-radius: 22px;
            padding: 22px;
            margin: 18px 0 24px 0;
            box-shadow: 0 10px 34px rgba(43,43,43,0.045);
        }}

        .chart-title {{
            font-size: 18px;
            font-weight: 850;
            color: {BURGUNDY};
            margin-bottom: 6px;
        }}

        .chart-caption {{
            font-size: 13px;
            color: {MUTED_TEXT};
            line-height: 1.55;
            margin-bottom: 18px;
        }}

        .funnel-row {{
            min-height: 46px;
            border-radius: 12px;
            margin: 10px auto;
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 10px 18px;
            color: white;
            font-weight: 750;
            box-shadow: 0 8px 20px rgba(58,7,28,0.10);
            gap: 16px;
        }}

        .matrix {{
            position: relative;
            height: 470px;
            background:
                linear-gradient(to right, transparent 49.8%, rgba(91,14,45,0.14) 50%, transparent 50.2%),
                linear-gradient(to bottom, transparent 49.8%, rgba(91,14,45,0.14) 50%, transparent 50.2%),
                #FFFFFF;
            border: 1px solid {BORDER_GREY};
            border-radius: 18px;
            overflow: hidden;
        }}

        .bubble {{
            position: absolute;
            width: 112px;
            min-height: 38px;
            padding: 7px 10px;
            border-radius: 999px;
            text-align: center;
            font-size: 11px;
            line-height: 1.25;
            font-weight: 800;
            box-shadow: 0 10px 24px rgba(91,14,45,0.16);
        }}

        .axis-label-x {{
            position: absolute;
            bottom: 12px;
            left: 50%;
            transform: translateX(-50%);
            color: {MUTED_TEXT};
            font-size: 12px;
            font-weight: 700;
        }}

        .axis-label-y {{
            position: absolute;
            top: 50%;
            left: -24px;
            transform: rotate(-90deg) translateY(-50%);
            transform-origin: left top;
            color: {MUTED_TEXT};
            font-size: 12px;
            font-weight: 700;
        }}

        .flow-grid {{
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 14px;
            align-items: stretch;
        }}

        .flow-card {{
            background: #FAFAFB;
            border: 1px solid {BORDER_GREY};
            border-radius: 18px;
            padding: 18px;
            min-height: 110px;
        }}

        .flow-card-dark {{
            background: linear-gradient(135deg, {BURGUNDY} 0%, {MID_BURGUNDY} 100%);
            color: white;
        }}

        .flow-label {{
            font-size: 13px;
            font-weight: 850;
            margin-bottom: 8px;
        }}

        .flow-note {{
            font-size: 12px;
            color: {MUTED_TEXT};
            line-height: 1.45;
        }}

        .flow-card-dark .flow-note {{
            color: rgba(255,255,255,0.82);
        }}

        .architecture-grid {{
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 14px;
        }}

        .architecture-card {{
            background: #FAFAFB;
            border: 1px solid {BORDER_GREY};
            border-radius: 18px;
            padding: 18px;
            min-height: 120px;
        }}

        .architecture-card.highlight {{
            background: linear-gradient(135deg, #FFF9EA 0%, #FFFFFF 100%);
            border: 1px solid rgba(201,162,39,0.45);
        }}

        .heatmap {{
            display: grid;
            grid-template-columns: 155px repeat(6, 1fr);
            border: 1px solid {BORDER_GREY};
            border-radius: 18px;
            overflow: hidden;
            background: white;
        }}

        .heat-cell {{
            padding: 12px 10px;
            border-right: 1px solid {BORDER_GREY};
            border-bottom: 1px solid {BORDER_GREY};
            font-size: 12px;
            font-weight: 750;
            text-align: center;
        }}

        .heat-head {{
            background: {BURGUNDY};
            color: white;
        }}

        .heat-row {{
            background: #FAFAFB;
            color: {BURGUNDY};
            text-align: left;
        }}

        .high {{
            background: {BURGUNDY};
            color: white;
        }}

        .medium {{
            background: {SOFT_ROSE};
            color: {DARK_TEXT};
        }}

        .low {{
            background: #F1E5E9;
            color: {MUTED_TEXT};
        }}

        .risk-grid {{
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 14px;
        }}

        .risk-card {{
            border: 1px solid {BORDER_GREY};
            border-radius: 18px;
            padding: 16px;
            background: #FAFAFB;
        }}

        .risk-band {{
            height: 9px;
            border-radius: 999px;
            margin-top: 12px;
            background: linear-gradient(90deg, {SOFT_ROSE}, {GOLD}, {BURGUNDY});
        }}

        .closing-panel {{
            background: linear-gradient(135deg, {BURGUNDY_DARK} 0%, {BURGUNDY} 100%);
            color: white;
            border-radius: 24px;
            padding: 34px 36px;
            box-shadow: 0 20px 55px rgba(58,7,28,0.24);
            margin-top: 18px;
        }}

        .closing-panel h2 {{
            color: white;
            margin-top: 0;
            font-size: 30px;
            line-height: 1.2;
        }}

        .closing-panel p, .closing-panel li {{
            color: rgba(255,255,255,0.88);
            line-height: 1.7;
            font-size: 15px;
        }}

        .footer-smr {{
            text-align: center;
            color: {MUTED_TEXT};
            font-size: 12px;
            padding: 20px 0 6px 0;
            border-top: 1px solid {BORDER_GREY};
            margin-top: 28px;
        }}

        .stTextInput input {{
            border-radius: 10px !important;
            border: 1px solid {BORDER_GREY} !important;
            height: 42px !important;
            font-size: 14px !important;
        }}

        .stButton > button {{
            background: linear-gradient(135deg, {BURGUNDY} 0%, {BURGUNDY_DARK} 100%) !important;
            color: white !important;
            border-radius: 10px !important;
            border: 0 !important;
            font-weight: 800 !important;
            min-height: 42px !important;
        }}

        @media (max-width: 900px) {{
            .kpi-grid,
            .flow-grid,
            .architecture-grid,
            .risk-grid {{
                grid-template-columns: repeat(1, minmax(0, 1fr));
            }}

            .hero {{
                padding: 30px;
            }}

            .hero h1 {{
                font-size: 30px;
            }}

            .heatmap {{
                grid-template-columns: 130px repeat(6, 145px);
                overflow-x: auto;
            }}

            .funnel-row {{
                width: 100% !important;
                flex-direction: column;
                align-items: flex-start;
            }}
        }}
        </style>
        """,
        unsafe_allow_html=True,
    )


# =============================================================================
# RENDERING HELPERS
# =============================================================================
def render_paragraph_line(line: str) -> str:
    cleaned = clean_and_mask(line.strip())

    if not cleaned:
        return ""

    if re.match(r"^\d{1,2}\.\d{1,2}\.?\s+", cleaned):
        return f"<div class='report-subheading'>{html.escape(cleaned)}</div>"

    if ":" in cleaned and len(cleaned.split(":")[0]) <= 55:
        left, right = cleaned.split(":", 1)
        return f"<p class='report-paragraph'><strong>{html.escape(left)}:</strong>{html.escape(right)}</p>"

    return f"<p class='report-paragraph'>{html.escape(cleaned)}</p>"


def build_table_html(table_title: str, table_lines: list[str]) -> str:
    table_match = re.search(r"TABLE\s+(\d+)", table_title, flags=re.I)
    if not table_match:
        return ""

    table_num = int(table_match.group(1))
    col_count = TABLE_COLUMN_COUNTS.get(table_num, 5)

    rows_source = [x.strip() for x in table_lines if x.strip()]

    if len(rows_source) < col_count:
        return ""

    headers = rows_source[:col_count]
    body = rows_source[col_count:]

    if len(body) % col_count != 0:
        body = body + [""] * (col_count - (len(body) % col_count))

    header_html = "".join(f"<th>{html.escape(clean_and_mask(h))}</th>" for h in headers)

    rows_html = ""
    for i in range(0, len(body), col_count):
        row = body[i: i + col_count]
        if not any(cell.strip() for cell in row):
            continue
        rows_html += "<tr>"
        for cell in row:
            rows_html += f"<td>{html.escape(clean_and_mask(cell))}</td>"
        rows_html += "</tr>"

    return f"""
    <div class="report-table-wrap">
        <div class="report-table-title">{html.escape(clean_and_mask(table_title))}</div>
        <table class="report-table">
            <thead><tr>{header_html}</tr></thead>
            <tbody>{rows_html}</tbody>
        </table>
    </div>
    """


def render_report_block(raw_text: str, stop_before_table=False):
    if not raw_text:
        st.markdown(
            """
            <div class="report-wrapper">
                <p class="report-paragraph">Content available in the full report.</p>
            </div>
            """,
            unsafe_allow_html=True,
        )
        return

    lines = raw_text.strip().splitlines()
    output = ["<div class='report-wrapper'>"]

    i = 0
    while i < len(lines):
        line = lines[i].strip()

        if not line:
            i += 1
            continue

        if re.match(r"^18\.2\.\s+Source Registry", line, flags=re.I):
            i += 1
            while i < len(lines) and not re.match(r"^18\.3\.", lines[i].strip()):
                i += 1
            continue

        if re.match(r"^TABLE\s+\d+:", line, flags=re.I):
            if stop_before_table:
                break

            table_title = line
            i += 1

            while i < len(lines) and not lines[i].strip():
                i += 1

            table_lines = []
            while i < len(lines):
                candidate = lines[i].strip()

                if not candidate:
                    break

                if candidate.startswith("## "):
                    break

                if re.match(r"^\d{1,2}\.\d{1,2}\.?\s+", candidate):
                    break

                if re.match(r"^TABLE\s+\d+:", candidate, flags=re.I):
                    break

                table_lines.append(candidate)
                i += 1

            output.append(build_table_html(table_title, table_lines))
            continue

        output.append(render_paragraph_line(line))
        i += 1

    output.append("</div>")

    st.markdown("\n".join(output), unsafe_allow_html=True)


def section_intro(title, subtitle=""):
    st.markdown(
        f"""
        <div class="section-card">
            <div class="section-title">{html.escape(title)}</div>
            {f'<div class="section-subtitle">{html.escape(subtitle)}</div>' if subtitle else ''}
        </div>
        """,
        unsafe_allow_html=True,
    )


def footer():
    st.markdown(
        """
        <div class="footer-smr">
            © 2026 Strategic Market Research. Confidential sample report preview prepared for Menarini.
            Full quantitative outputs available in the complete report.
        </div>
        """,
        unsafe_allow_html=True,
    )


# =============================================================================
# LOGIN
# =============================================================================
def login_screen():
    st.markdown("<div style='height:10vh;'></div>", unsafe_allow_html=True)
    c1, c2, c3 = st.columns([1.2, 1.0, 1.2])

    with c2:
        st.markdown(
            f"""
            <div style="background:{WHITE};border:1px solid {BORDER_GREY};border-radius:22px;padding:26px 28px;box-shadow:0 18px 48px rgba(58,7,28,0.10);">
                <div style="text-align:center;font-size:24px;font-weight:900;color:{BURGUNDY};letter-spacing:-0.02em;">Strategic Market Research</div>
                <div style="text-align:center;font-size:12px;font-weight:800;color:{GOLD};letter-spacing:0.08em;text-transform:uppercase;margin-top:6px;margin-bottom:18px;">Secure Client Preview</div>
                <div style="text-align:center;font-size:13px;color:{MUTED_TEXT};line-height:1.5;margin-bottom:18px;">
                    Confidential sample report dashboard prepared for Menarini.
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )

        with st.form("login_form", clear_on_submit=False):
            username = st.text_input("Username", placeholder="SMR")
            password = st.text_input("Password", type="password", placeholder="SMR@2026")
            login_btn = st.form_submit_button("Enter Dashboard", use_container_width=True)

        if login_btn:
            if username == USERNAME and password == PASSWORD:
                st.session_state["logged_in"] = True
                st.rerun()
            else:
                st.error("Invalid username or password.")


# =============================================================================
# PURE HTML / CSS VISUALS — NO SVG
# =============================================================================
def chart_tam_sam_som_funnel():
    st.markdown(
        f"""
        <div class="chart-card">
            <div class="chart-title">TAM / SAM / SOM Funnel</div>
            <div class="chart-caption">
                The full report quantifies each market layer. This preview masks proprietary values while preserving the narrowing logic.
            </div>
            <div class="funnel-row" style="width:100%;background:{BURGUNDY};">
                <span>Lipid-Lowering Therapy Revenue Pool</span><span>US$ [Proprietary]</span>
            </div>
            <div class="funnel-row" style="width:84%;background:{MID_BURGUNDY};">
                <span>CETP-Relevant Opportunity</span><span>US$ [Proprietary]</span>
            </div>
            <div class="funnel-row" style="width:66%;background:{SOFT_ROSE};color:{DARK_TEXT};">
                <span>Obicetrapib-Addressable Pool</span><span>US$ [Proprietary]</span>
            </div>
            <div class="funnel-row" style="width:48%;background:{GOLD};color:{DARK_TEXT};">
                <span>Menarini Commercial Opportunity</span><span>US$ [Proprietary]</span>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def chart_competitive_matrix():
    bubbles = [
        ("Statins", 72, 68, BURGUNDY_DARK),
        ("Ezetimibe", 61, 62, MID_BURGUNDY),
        ("PCSK9 mAbs", 54, 24, GOLD),
        ("Inclisiran", 44, 30, SOFT_ROSE),
        ("Bempedoic Acid", 48, 56, MID_BURGUNDY),
        ("Obicetrapib", 64, 19, BURGUNDY),
        ("Obicetrapib + Ezetimibe FDC", 50, 16, BURGUNDY),
        ("Other CETP", 25, 34, SOFT_ROSE),
    ]

    bubble_html = ""
    for label, left, top, color in bubbles:
        text_color = DARK_TEXT if color in [GOLD, SOFT_ROSE] else WHITE
        bubble_html += (
            f"<div class='bubble' style='left:{left}%;top:{top}%;"
            f"background:{color};color:{text_color};'>{html.escape(label)}</div>"
        )

    st.markdown(
        f"""
        <div class="chart-card">
            <div class="chart-title">Competitive Intensity vs Differentiation Matrix</div>
            <div class="chart-caption">
                Therapy classes are positioned qualitatively. No numeric scores are disclosed in this sample preview.
            </div>
            <div class="matrix">
                {bubble_html}
                <div class="axis-label-x">Commercial maturity →</div>
                <div class="axis-label-y">LDL-C differentiation / residual-risk relevance →</div>
                <div style="position:absolute;left:12px;top:10px;color:{MUTED_TEXT};font-size:12px;font-weight:700;">High differentiation / lower maturity</div>
                <div style="position:absolute;right:12px;bottom:34px;color:{MUTED_TEXT};font-size:12px;font-weight:700;">High maturity / lower differentiation</div>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def chart_commercial_pathway():
    st.markdown(
        f"""
        <div class="chart-card">
            <div class="chart-title">Commercialization Pathway Map</div>
            <div class="chart-caption">
                Directional patient-to-revenue conversion logic. No proprietary patient counts or revenue values are disclosed.
            </div>
            <div class="flow-grid">
                <div class="flow-card flow-card-dark">
                    <div class="flow-label">High-risk dyslipidemia patients</div>
                    <div class="flow-note">Broad clinical need pool</div>
                </div>
                <div class="flow-card">
                    <div class="flow-label">Uncontrolled LDL-C despite standard therapy</div>
                    <div class="flow-note">Narrowed by goal non-attainment and treatment intensification gap</div>
                </div>
                <div class="flow-card">
                    <div class="flow-label">CETP-eligible opportunity</div>
                    <div class="flow-note">Filtered by label, HTA access and specialist reach</div>
                </div>
                <div class="flow-card flow-card-dark">
                    <div class="flow-label">Menarini commercial opportunity</div>
                    <div class="flow-note">Obicetrapib mono + obicetrapib / ezetimibe FDC</div>
                </div>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def chart_transition_map():
    st.markdown(
        f"""
        <div class="chart-card">
            <div class="chart-title">Therapy Class Transition Map</div>
            <div class="chart-caption">
                The lipid-lowering landscape is moving from generic volume therapy toward high-efficacy, specialist-led and next-generation oral intensification options.
            </div>
            <div class="flow-grid">
                <div class="flow-card flow-card-dark">
                    <div class="flow-label">Generic baseline therapy</div>
                    <div class="flow-note">Statins and low-cost established backbone</div>
                </div>
                <div class="flow-card">
                    <div class="flow-label">Add-on oral therapy</div>
                    <div class="flow-note">Ezetimibe and branded oral non-statin options</div>
                </div>
                <div class="flow-card">
                    <div class="flow-label">Injectable / long-acting escalation</div>
                    <div class="flow-note">PCSK9 mAbs and inclisiran set the high-efficacy benchmark</div>
                </div>
                <div class="flow-card flow-card-dark">
                    <div class="flow-label">Next-generation oral CETP / FDC</div>
                    <div class="flow-note">Potential oral biologic-like intensification step</div>
                </div>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def chart_value_architecture():
    items = [
        ("Epidemiology", "Defines high-risk and uncontrolled LDL-C pools"),
        ("Treatment Revenue Pools", "Frames practical TAM and budget substitution logic"),
        ("LDL-C Gap", "Identifies the goal non-attainment demand engine"),
        ("CETP Clinical Evidence", "Supports class revival and obicetrapib differentiation"),
        ("Pricing Benchmarks", "Positions oral branded therapy against injectables and add-ons"),
        ("Regulatory Timing", "Links approval, reimbursement and launch activation"),
        ("Competitive Landscape", "Maps substitution pressure and therapy-class threats"),
        ("Adoption Readiness", "Assesses physician, payer and specialist pathway friction"),
        ("Menarini Strategy", "Converts market evidence into launch and value-capture decisions"),
    ]

    cards = ""
    for idx, (title, note) in enumerate(items):
        cls = "architecture-card highlight" if idx in [3, 8] else "architecture-card"
        cards += f"""
        <div class="{cls}">
            <div class="flow-label">{html.escape(title)}</div>
            <div class="flow-note">{html.escape(note)}</div>
        </div>
        """

    st.markdown(
        f"""
        <div class="chart-card">
            <div class="chart-title">Report Value Architecture</div>
            <div class="chart-caption">
                The full report converts research inputs into Menarini-specific strategic decisions.
            </div>
            <div class="architecture-grid">
                {cards}
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def chart_heatmap():
    rows = {
        "Europe": ["High", "High", "Medium", "High", "High", "Medium"],
        "United Kingdom": ["High", "High", "Medium", "High", "Medium", "High"],
        "Switzerland": ["High", "Medium", "Medium", "High", "High", "Medium"],
        "United States": ["Medium", "High", "High", "High", "Low", "High"],
        "Japan": ["Medium", "Medium", "Medium", "Medium", "Low", "Medium"],
        "China": ["Medium", "High", "Medium", "Medium", "Medium", "Medium"],
        "Rest of World": ["Low", "Low", "Low", "Low", "Low", "Low"],
    }

    cols = [
        "Reimbursement",
        "LDL-C Gap",
        "Specialist Adoption",
        "Pricing Potential",
        "Menarini Fit",
        "Competitive Pressure",
    ]

    grid = "<div class='heatmap'><div class='heat-cell heat-head'>Region</div>"
    for c in cols:
        grid += f"<div class='heat-cell heat-head'>{html.escape(c)}</div>"

    for region, vals in rows.items():
        grid += f"<div class='heat-cell heat-row'>{html.escape(region)}</div>"
        for v in vals:
            grid += f"<div class='heat-cell {v.lower()}'>{v}</div>"

    grid += "</div>"

    st.markdown(
        f"""
        <div class="chart-card">
            <div class="chart-title">Regional Launch Readiness Heatmap</div>
            <div class="chart-caption">
                Qualitative readiness view across launch-relevant markets.
            </div>
            {grid}
        </div>
        """,
        unsafe_allow_html=True,
    )


def chart_risk():
    items = [
        ("Regulatory timing", "High control requirement"),
        ("Payer acceptance", "HTA-sensitive"),
        ("Competitive displacement", "Substitution pressure"),
        ("Physician adoption", "Education-dependent"),
        ("FDC differentiation", "Value-capture lever"),
        ("Pricing discipline", "Net-price sensitivity"),
        ("Evidence durability", "CVOT-linked upside"),
        ("Class skepticism", "Legacy CETP barrier"),
    ]

    cards = ""
    for title, note in items:
        cards += f"""
        <div class="risk-card">
            <div class="flow-label">{html.escape(title)}</div>
            <div class="flow-note">{html.escape(note)}</div>
            <div class="risk-band"></div>
        </div>
        """

    st.markdown(
        f"""
        <div class="chart-card">
            <div class="chart-title">Risk vs Control Dashboard</div>
            <div class="chart-caption">
                Directional risk map. Exact risk scores and sensitivity outputs are available in the full report.
            </div>
            <div class="risk-grid">
                {cards}
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


# =============================================================================
# PAGES
# =============================================================================
def render_cover():
    st.markdown(
        f"""
        <div class="hero">
            <div class="hero-kicker">Confidential Sample Report Preview</div>
            <h1>Global CETP Inhibitors Market Preview</h1>
            <h2>2025–2035: Obicetrapib, Next-Generation Lipid-Lowering Therapy & Strategic Positioning for Menarini</h2>
            <p>
                Prepared by <b>Strategic Market Research</b> for <b>Menarini</b>.
                This dashboard previews the report architecture, strategic logic, competitive framing and commercialization implications.
                All proprietary market values, patient counts, percentages and forecast outputs are intentionally masked.
            </p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.markdown(
        """
        <div class="kpi-grid">
            <div class="kpi-card"><div class="kpi-label">Global Market Opportunity</div><div class="kpi-value">US$ [Proprietary]</div><div class="kpi-note">Full value available in complete report</div></div>
            <div class="kpi-card"><div class="kpi-label">Europe / UK / Switzerland SAM</div><div class="kpi-value">US$ [Proprietary]</div><div class="kpi-note">CETP-addressable opportunity</div></div>
            <div class="kpi-card"><div class="kpi-label">Menarini SOM Potential</div><div class="kpi-value">US$ [Proprietary]</div><div class="kpi-note">Launch-driven territory capture</div></div>
            <div class="kpi-card"><div class="kpi-label">Launch Window</div><div class="kpi-value">[Available in Full Report]</div><div class="kpi-note">Regulatory and reimbursement timing</div></div>
            <div class="kpi-card"><div class="kpi-label">Eligible Patient Pool</div><div class="kpi-value">[Proprietary] patients</div><div class="kpi-note">High-risk uncontrolled LDL-C pool</div></div>
            <div class="kpi-card"><div class="kpi-label">Forecast Horizon</div><div class="kpi-value">2025–2035</div><div class="kpi-note">Commercial forecast period</div></div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    section_intro(
        "Executive Thesis",
        "CETP inhibitors are being repositioned from a historically challenged mechanism into a potential next-generation oral lipid-lowering category.",
    )
    render_report_block(get_section(1, "Executive Overview"), stop_before_table=True)
    chart_tam_sam_som_funnel()
    chart_competitive_matrix()


def render_market_architecture():
    section_intro(
        "Market Architecture",
        "The report separates the practical lipid-lowering therapy budget pool from the SAM and SOM available to CETP inhibitors after regulatory approval and payer access.",
    )
    render_report_block(get_section(2, "Market Definition"))
    chart_tam_sam_som_funnel()


def render_opportunity_logic():
    section_intro(
        "CETP Inhibitor Opportunity Logic",
        "Obicetrapib reframes the CETP class by addressing historical potency and safety concerns while targeting the uncontrolled LDL-C gap.",
    )
    render_report_block(get_section(3, "CETP Mechanism"))
    chart_commercial_pathway()
    chart_transition_map()


def render_menarini_fit():
    section_intro(
        "Menarini / Obicetrapib Strategic Fit",
        "Menarini’s commercial opportunity is tied to successful HTA navigation, evidence-led physician education and territory-specific launch sequencing.",
    )
    render_report_block(get_section(14, "Menarini Opportunity"))
    chart_value_architecture()


def render_tam_preview():
    section_intro(
        "TAM / SAM / SOM Preview",
        "The full report provides year-by-year quantitative tables, but this sample preview masks all values to preserve proprietary model outputs.",
    )
    render_report_block(get_section(10, "Market Size"))
    chart_tam_sam_som_funnel()
    chart_commercial_pathway()


def render_competitive():
    section_intro(
        "Competitive Landscape",
        "Direct CETP competition is limited, but substitute pressure from statins, ezetimibe, bempedoic acid, PCSK9 mAbs and inclisiran shapes adoption ceilings.",
    )
    render_report_block(get_section(12, "Competitive Landscape"))
    chart_competitive_matrix()
    chart_transition_map()


def render_regulatory():
    section_intro(
        "Clinical & Regulatory Readiness",
        "Approval timing, label breadth and outcomes evidence are critical variables in the forecast.",
    )
    render_report_block(get_section(7, "Clinical Evidence"))
    render_report_block(get_section(8, "Regulatory Pathway"))


def render_pricing_access():
    section_intro(
        "Pricing, Access & Adoption",
        "Pricing strategy must navigate between low-cost generic add-ons and high-cost injectables while building a payer case for an oral biologic-like step.",
    )
    render_report_block(get_section(9, "Pricing"))
    render_report_block(get_section(13, "Adoption Dynamics"))


def render_region():
    section_intro(
        "Regional Launch Prioritization",
        "Germany and the UK anchor Wave 1 commercialization, while France, Switzerland, Italy and Spain shape mid-term expansion.",
    )
    render_report_block(get_section(11, "Europe"))
    chart_heatmap()


def render_risk():
    section_intro(
        "Risk, Barriers & Watchpoints",
        "The most important downside risks relate to restrictive labeling, payer filters, CETP class skepticism and FDC timing.",
    )
    render_report_block(get_section(15, "Scenario Analysis"))
    render_report_block(get_section(16, "Risk Assessment"))
    chart_risk()


def render_strategy():
    section_intro(
        "Strategic Roadmap & Recommendations",
        "The commercial roadmap moves from approval preparation and Wave 1 launch to Wave 2 scaling and outcomes-supported broader adoption.",
    )
    render_report_block(get_section(17, "Strategic Roadmap"))
    chart_value_architecture()


def render_closing():
    st.markdown(
        f"""
        <div class="closing-panel">
            <h2>Why Menarini Should Access the Full Report</h2>
            <p>
                The CETP inhibitors market is not a conventional lipid-lowering category. It is a revived mechanism entering a crowded, payer-disciplined market where success depends on proving that obicetrapib can create biologic-like efficacy through an oral, commercially scalable model.
            </p>
            <p>
                Obicetrapib’s opportunity depends on identifying the right uncontrolled LDL-C patient segments, the right launch sequence, the right reimbursement argument and the right differentiation against statins, ezetimibe, bempedoic acid, PCSK9 mAbs and inclisiran.
            </p>
            <ul>
                <li>The full report unlocks complete market size, SAM and SOM values by year and geography.</li>
                <li>It provides country-level access logic for Europe, the UK and Switzerland.</li>
                <li>It benchmarks obicetrapib and the FDC against current and emerging lipid-lowering therapies.</li>
                <li>It converts clinical, regulatory, payer and competitive complexity into actionable launch decisions.</li>
                <li>The sample dashboard intentionally masks proprietary values; the full report provides the complete quantitative model.</li>
            </ul>
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_full_report():
    section_intro(
        "Full Report Summary Explorer",
        "Every section from the embedded report summary is shown below with market-sensitive values masked and tables rendered as structured exhibits.",
    )

    query = st.text_input(
        "Search report summary",
        placeholder="Example: obicetrapib, HTA, Germany, SAM, FDC, PCSK9",
    )

    show_all = st.toggle("Show complete summary in one continuous view", value=False)

    if show_all:
        for title, content in REPORT_SECTIONS.items():
            if title == "Cover / Report Title":
                continue

            st.markdown(
                f"<div class='section-title' style='margin-top:28px;'>{html.escape(title)}</div>",
                unsafe_allow_html=True,
            )
            render_report_block(content)
    else:
        for title, content in REPORT_SECTIONS.items():
            if title == "Cover / Report Title":
                continue

            combined = f"{title}\n{content}"
            if query.strip() and query.lower() not in combined.lower():
                continue

            with st.expander(title, expanded=False):
                render_report_block(content)


# =============================================================================
# MAIN
# =============================================================================
def main():
    inject_css()

    if "logged_in" not in st.session_state:
        st.session_state["logged_in"] = False

    if not st.session_state["logged_in"]:
        login_screen()
        footer()
        return

    with st.sidebar:
        st.markdown(
            f"""
            <div style="padding:10px 0 18px 0;">
                <div style="font-size:20px;font-weight:900;color:white;">Strategic Market Research</div>
                <div style="font-size:11px;font-weight:800;color:{GOLD};letter-spacing:0.08em;text-transform:uppercase;margin-top:5px;">Menarini CETP Preview</div>
            </div>
            """,
            unsafe_allow_html=True,
        )

        page = st.radio(
            "Dashboard sections",
            [
                "Cover & Executive Snapshot",
                "Market Architecture",
                "CETP Inhibitor Opportunity Logic",
                "Menarini / Obicetrapib Strategic Fit",
                "TAM / SAM / SOM Preview",
                "Competitive Landscape",
                "Clinical & Regulatory Readiness",
                "Pricing, Access & Adoption",
                "Regional Launch Prioritization",
                "Risk, Barriers & Watchpoints",
                "Strategic Recommendations",
                "Why Menarini Should Access the Full Report",
                "Full Report Summary Explorer",
            ],
            label_visibility="collapsed",
        )

        st.markdown("<hr style='border-color:rgba(255,255,255,0.18);'>", unsafe_allow_html=True)

        if st.button("End Secure Session", use_container_width=True):
            st.session_state["logged_in"] = False
            st.rerun()

    if page == "Cover & Executive Snapshot":
        render_cover()
    elif page == "Market Architecture":
        render_market_architecture()
    elif page == "CETP Inhibitor Opportunity Logic":
        render_opportunity_logic()
    elif page == "Menarini / Obicetrapib Strategic Fit":
        render_menarini_fit()
    elif page == "TAM / SAM / SOM Preview":
        render_tam_preview()
    elif page == "Competitive Landscape":
        render_competitive()
    elif page == "Clinical & Regulatory Readiness":
        render_regulatory()
    elif page == "Pricing, Access & Adoption":
        render_pricing_access()
    elif page == "Regional Launch Prioritization":
        render_region()
    elif page == "Risk, Barriers & Watchpoints":
        render_risk()
    elif page == "Strategic Recommendations":
        render_strategy()
    elif page == "Why Menarini Should Access the Full Report":
        render_closing()
    elif page == "Full Report Summary Explorer":
        render_full_report()

    footer()


if __name__ == "__main__":
    main()
